### ISSUE TITLE
Support For Django 1.9 In pip installed package

### ISSUE THREAD

**Issue by sorter** [django-notifications/django-notifications#108]
Two things seem to be true about the version of django-notifications-hq which pip installs:

1. It's incompatible with django 1.9
2. The source isn't the same as what's presently in the git repo, for example __init__.py

Am I missing something? Or will it take some time until a compatible version makes it into pip?

**Comment by yangyubo** [comment]
@sorter The latest pip version was on [0.8.x branch](https://github.com/django-notifications/django-notifications/tree/0.8.x), the master is Django 1.9 compatible but not yet released.

I suggest you use master for now, and waiting next version to be released.

For more info about next release: #89

**Comment by sorter** [comment]
@yangyubo Thank you!
