### ISSUE TITLE
Lack of AJAX functionality

### ISSUE THREAD

**Issue by pythad** [django-notifications/django-notifications#116]
Hi, great package, thanks for it, good job!

In my opinion it doesn't have some ajax functionality. It's not the good idea to re render and redirect a user to the same page after marking a single `notice` as read. It would be nice to add this functionality as in most cases we use this marking buttons near the notice and don't want to reload the page.

I think it's possible to check if `request.is_ajax()` in views and perform certain actions. What are your thoughts on this?

**Comment by LegoStormtroopr** [comment]
Is what context are you thinking for this?
