### ISSUE TITLE
Live update template

### ISSUE THREAD

**Issue by joke2k** [django-notifications/django-notifications#117]
Hi, thank you for this package.
I would like to use the live update callback to build github-like notification on a bootstrapped dropdown menu but the object returned from api/unread_list does not contains the urls that I have to use to build the hrefs.
How i can reproduce the main example in README (with links)?
justquick (actor) closed (verb) issue 2 (object) on activity-stream (target) 12 hours ago

p.s. i've to convert the timestamp also in timesince.

**Comment by zubhav** [comment]
In settings.py, add NOTIFICATIONS_USE_JSONFIELD = True. Then, in your notify.send() you can add any extra argument. E.g. notify.send(.... href="/site/home"). You can access this in your template by using {{ notification.data.href }} . 

To access it in JS (fill_notification_list()) you can use:
if(item.data != null){
            	var json_data = JSON.parse(item.data);
                var href = json_data.href;
}

**Comment by AlvaroLQueiroz** [comment]
As @zubhav said, you should use the extra data option. From version 1.3+ you do not need to parse the data field.

**Comment by goromachine** [comment]
I know this thread is old, but I'm issuing the problem the author asks on it's p.s. `i've to convert the timestamp also in timesince.`. 

How we are supposed to do that, is there any simple way of doing this? 
Thank you.
