### ISSUE TITLE
pypi installation has migration errors

### ISSUE THREAD

**Issue by JamSquad** [django-notifications/django-notifications#119]
Not sure if the actual 1.0 is released on the pypi.  The error is the migration file is using ```notifications.now``` when it should be using ```django.utils.timezone.now```.  I see it's fixed in the source here, but pypi still includes the reference to ```notifications.now```

Using the 1.0 release.

**Comment by yangyubo** [comment]
@JamSquad Thanks for reporting, will fix it in next release.

**Comment by adamn** [comment]
If you could get a new release out for this it would be great.  Kind of an annoying problem when running our own migrations.

**Comment by yangyubo** [comment]
@adamn  @JamSquad  I've pushed a new release (1.1) to PyPI, please give it a try and let me know if it still has error while migrating.
