### ISSUE TITLE
Make recipient field's related_name dynamic in the Notification model

### ISSUE THREAD

**Issue by ghost** [django-notifications/django-notifications#122]
Hi,

I'm trying to customize the `Notification` model to suit my requirements but found that the [related_name](https://github.com/django-notifications/django-notifications/blob/master/notifications/models.py#L153) in `recipient` is hard-coded. According to [Django's best practice](https://docs.djangoproject.com/en/dev/topics/db/models/#be-careful-with-related-name-and-related-query-name), is it possible to give a switch over to specify the related_name by having a settings variable like NOTIFICATION_APP_NAME? Also the model can be set abstract?

```
DEFAULT_APP_NAME = "notifications"
NOTIFICATION_APP_NAME = getattr(settings, 'NOTIFICATION_APP_NAME', DEFAULT_APP_NAME)
```

```
if settings.NOTIFICATION_APP_NAME != DEFAULT_APP_NAME:
    recipient_related_name = "%(app_label)s_%(class)s"
else:
    recipient_related_name = "notifications"
```

Or just overriding the `recipient` field with some other `related_name` will work?

**Comment by yangyubo** [comment]
@babus Thank you for pointing out, would you please file a PR for this?

**Comment by AlvaroLQueiroz** [comment]
Fixed on [version 2](https://github.com/django-notifications/django-notifications/tree/v2-alpha) [b1827ca](https://github.com/django-notifications/django-notifications/commit/b1827ca5318fb345a2cb322986f212f42e0f47ea)
