### ISSUE TITLE
Template tag issue

### ISSUE THREAD

**Issue by rileywiley** [django-notifications/django-notifications#124]
Hey, 
I just decided to implement this and I am getting the following error:
`'notifications_unread' tag takes at least 2 arguments and the second last argument must be 'as'
`
Can you tell me what I could be doing wrong. I have implemented the {% notifications_unread %} in the base template and that seemed to break everything. Suggestions?

**Comment by zubhav** [comment]
I think I encountered a similar problem earlier. You have to give it a name like
{% notifications_unread as some_name %}
