### ISSUE TITLE
Mark All As read fails if soft-deleted

### ISSUE THREAD

**Issue by ericsonmichaelj** [django-notifications/django-notifications#126]
Running this code didn't cause the items to be marked as read if they were already considered soft-deleted. 
`        request.user.notifications.mark_all_as_read()
`

I had to work around it through the following code.
`
        request.user.notifications.mark_all_as_active()
        request.user.notifications.mark_all_as_read()
        request.user.notifications.mark_all_as_deleted()
`

**Comment by zhang-z** [comment]
@ericsonmichaelj , I'm not very sure whether it's necessary to mark soft-deleted as read. Consider gmail, I usually just mark all as read for all "Inbox" conversations, don't really care about the ones in trash. Anyway, I created pull request #127 for this issue
