### ISSUE TITLE
'module' object has no attribute 'urls'

### ISSUE THREAD

**Issue by imatsu** [django-notifications/django-notifications#128]
I'm trying django-notifications in a virtual environment with django v1.9 , when I add the url and run the server, the following error

```
url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
AttributeError: 'module' object has no attribute 'urls'
```

**Comment by felipemechailech** [comment]
Just put quotes in notifications.urls, this way: url('^inbox/notifications/', include('notifications.urls', namespace='notifications')),

**Comment by imatsu** [comment]
Excelent, thank you very much,
