### ISSUE TITLE
Multiple recipients

### ISSUE THREAD

**Issue by zubhav** [django-notifications/django-notifications#129]
Groups can be used for the recipient argument in notify.send(..). Is there a way for it to accept a queryset of the User model?

**Comment by Echel8n** [comment]
Did you find an answer or an implementation which is not a loop ?

**Comment by Worldrider** [comment]
ManyToMany with extra fields (unread, emailed) I guess
https://docs.djangoproject.com/en/dev/topics/db/models/#extra-fields-on-many-to-many-relationships

**Comment by AlvaroLQueiroz** [comment]
Fixed in #173!
