### ISSUE TITLE
Missing migration in PyPi version

### ISSUE THREAD

**Issue by Egregors** [django-notifications/django-notifications#138]
The migrations in this repo and migrations in PyPi are different. 
0005 migration is missing. It completely broke CI process.

Can you push missing migration into PyPi, please?

**Comment by LegoStormtroopr** [comment]
I'll check this out this weekend.

**Comment by yangyubo** [comment]
@LegoStormtroopr I've checked repo, the missing migration actually was already pushed into repo by #132 . So I think what we need todo is just release the latest code into PyPi.

@Egregors am I understand you right?

**Comment by Egregors** [comment]
@yangyubo yep, absolutely.

**Comment by Egregors** [comment]
Right now I can't make my own migrations in CI process because Django raises error 

```
"Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them."
```

So, missing migrations in third party apps may become a hard findable cause of deployment failure. 

Thanks for so quick reply (=

**Comment by yangyubo** [comment]
@Egregors done, please check https://pypi.python.org/pypi/django-notifications-hq
