### ISSUE TITLE
javascript API to make as read

### ISSUE THREAD

**Issue by Shyghar** [django-notifications/django-notifications#139]
Hi, 
I want to 'mark as read' the notification when the user open the dropdown menu but I'm not understanding witch URL call to do that.

Can someone help me to understand how can I do this?

**Comment by zhang-z** [comment]
Hi @Shyghar , you can call: `[PREFIX]mark-all-as-read/` for mark all notifications or `[PREFIX]mark-as-read/(?P<slug>\d+)/` for mark a specific notification.

The [PREFIX] is the one you defined in your root urls.py. Take below as example:

    urlpatterns = [
        ...
        url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
        ...
    ]

In this case, the [PREFIX] is "/inbox/notifications/".

Currently the README doesn't talk so detailed about URLs yet. So you may just refer to source code: https://github.com/django-notifications/django-notifications/blob/master/notifications/urls.py

**Comment by KhanMaytok** [comment]
Where is the slug?

**Comment by Echel8n** [comment]
**slug =  id + 110909**

**Comment by Samoht1** [comment]
how the hell do I create that slug??
