### ISSUE TITLE
Using Notifications Variable in Template

### ISSUE THREAD

**Issue by skizzy** [django-notifications/django-notifications#142]
Hello, I want to check each verb in order to display different messages to user. I iterated over the 

> 'notifications

' but it's not working. Only this tag 

> {% notifications_unread %}

 is working. And for me, it's not enough.

```
`    {% for notice in notifications %}
             <p>msg </p>

                 {% if notice.verb == "host reply" %}

             <p> {{notice.actor}} sent you a message {{notice.timetamp|timesince}} . View Inbox </p>

               {% elif notice.verb == "mover reply" %}
                     <p> msgg </p>
                    <p> {{notice.actor}} sent you a  message {{notice.timetamp|timesince}} . View Messages                            </p>
              {% else %}
             <p> no notification </p>
               {% endif %}
        {% endfor %}`
```

What am I missing?

**Comment by cawjustin** [comment]
`notifications` has to come from the view context. You have to get a query set of notifications in the view and add it to the context.

**Comment by AlvaroLQueiroz** [comment]
@skizzy were you able to solve this? Was the queryset in context?
