### ISSUE TITLE
Django JSONField for Postgres

### ISSUE THREAD

**Issue by marcgibbons** [django-notifications/django-notifications#152]
Hello - what are your thoughts on adding feature detection for the `data` model field which could default to use Django's contrib postgres JSONField when using postgres / DJ 1.9+ and fallback to django-jsonfield for other backends?

**Comment by LegoStormtroopr** [comment]
What would be the use of this?
I'm afraid I don't understand what this would change or do?

**Comment by jotes** [comment]
@LegoStormtroopr From what I understand, the current implementation of JsonField provided by the JsonField package, doesn't allow to do queries. Look here: https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#querying-jsonfield

**Comment by psychok7** [comment]
This PR should take care of this once it is merged: https://github.com/django-notifications/django-notifications/pull/160

**Comment by AlvaroLQueiroz** [comment]
Fixed on [version 2](/django-notifications/django-notifications/tree/v2-alpha)
