### ISSUE TITLE
Add kwargs support for mark_as_read(unread) views

### ISSUE THREAD

**Issue by zmrenwu** [django-notifications/django-notifications#154]
In current version, the mark_as_read(unread) views only accept a request argument. Sometimes people would add another argument in their URL pattern. For example: /(?P<username>).+/notifications. But now the views can't handle this argument. Add the **kwargs in views would solve this problem. Such as:

```
def mark_as_read(request,*args,**kwargs):
    ...
```

**Comment by AlvaroLQueiroz** [comment]
@zmrenwu I do not understand the utility of this, because even if the view receives other arguments, they will not be useful. Could you explain me better?

**Comment by zmrenwu** [comment]
Just some parameters hook. Also the better solution is write a custom view. So there's noting to do.
