### ISSUE TITLE
Slug and ID

### ISSUE THREAD

**Issue by lirilla** [django-notifications/django-notifications#155]
Hello!

I have a question about API. 
It returns notification JSON without slug, only id, although slug returns in templates. 
I tried to use mark-as-read method, but I had to send id + 110909 as slug parameter in URL in my JS code . Is it possible to include slug parameter in API? Or, what am I doing wrong?

Thank you.

**Comment by smendez-hi** [comment]
I have the same problem. I though ID and slug where the same but no. I want to use the "delete" method in javascript but i can't without the slug.

**Comment by rajat404** [comment]
+1
Using [django-autoslug](https://pypi.python.org/pypi/django-autoslug) would be a better option.

**Comment by yangyubo** [comment]
Patches are welcome ;)
