### ISSUE TITLE
update release in pypi with current master

### ISSUE THREAD

**Issue by andreip** [django-notifications/django-notifications#159]
Even though the final commit is https://github.com/django-notifications/django-notifications/commit/99dfa0a81873e9916e4e95c0d04d7a5376f8104b in master ; the latest pypi release (`django-notifications-hq==1.2`) doesn't contain that -- and that's quite useful parameter to use.

**Comment by bcb** [comment]
Also need to tag version 1.2 in the git tags.

It only has a tag for 1.1, so I can't checkout the latest stable release.

**Comment by AlvaroLQueiroz** [comment]
Version 1.3 is already available in pypi.
