### ISSUE TITLE
notifications_unread is really slow if there are a lot of notifications

### ISSUE THREAD

**Issue by italomaia** [django-notifications/django-notifications#164]
notifications_unread is quite slow if the number of notifications is big. It would be nice if there was a way to check if the user has new notifications without actually couting them. Maybe calling exists ...

**Comment by jotes** [comment]
@italomaia Hi, what do you mean by "actually counting them" - is count() method too slow? Did you thought about database-index?

**Comment by italomaia** [comment]
Yeap; count is very slow and index won't help much.

**Comment by AlvaroLQueiroz** [comment]
Good suggestion @italomaia. A new template tag is very interesting. If you can send us a PR, we really appreciate that.
