### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by Egregors** [django-notifications/django-notifications#167]
Hi, and thanks alot for your project.

I have a architecture question: why did you implement `notify()` functions as signal, but not Notification class method or just function?

I ask because I working on kind of littel bit similar project right now, and me very interest, why are you deside make it this way.

Thanks.

**Comment by Egregors** [comment]
So, you just close issue without any single word.
Well done, keep it up

**Comment by AlvaroLQueiroz** [comment]
@Egregors, i can't help you with this question and I believe that the author will not answer, since it is already past one year.
