### ISSUE TITLE
custom context how-to

### ISSUE THREAD

**Issue by cjdcordeiro** [django-notifications/django-notifications#168]
Hi,

question: I'm trying to override the list.html template but I need to pass my own context id addition to just the defaults 'notifications'.

How can I do this? I see that class NotificationViewList(ListView) does not have a get_context* method...so even with decorators I'm not able to override the view myself...

**Comment by AlvaroLQueiroz** [comment]
You can use a [context-processor](https://docs.djangoproject.com/en/1.8/topics/templates/#context-processors) or rewrite the notifications views.
