### ISSUE TITLE
Question: Use with uuid

### ISSUE THREAD

**Issue by khankuan** [django-notifications/django-notifications#170]
Hi, I'm trying to use uuid for id instead of integer. 
```
class MyNotification(Notification):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

However, I've gonna the following error:
```
The field 'id' clashes with the field 'id' from model 'notifications.notification'.
```
Is there a way to use uuids instead? Thanks!

**Comment by AlvaroLQueiroz** [comment]
It's not possible to override model fields.
https://docs.djangoproject.com/en/1.11/topics/db/models/#field-name-hiding-is-not-permitted
