### ISSUE TITLE
question: force refresh on live_notify_badge

### ISSUE THREAD

**Issue by cjdcordeiro** [django-notifications/django-notifications#171]
Hi,

how can one trigger a refresh, manually (from an event), to the live_notify_badge and list as well? 

Just calling the function fetch_api_data() makes the refresh happen but it only happens for the first {% live_notify_badge %} tag.

**Comment by AlvaroLQueiroz** [comment]
@cjdcordeiro you have more than one badge in same page? Are you using standard callbacks `{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}`?
