### ISSUE TITLE
version 1.3 in pip

### ISSUE THREAD

**Issue by theromis** [django-notifications/django-notifications#174]
Hi,

is it possible to release updated version? I need all the changes maiden after 1.2

**Comment by yangyubo** [comment]
@theromis volunteers wanted. Would you interested in becoming `django-notification` package maintainer ?

**Comment by theromis** [comment]
@yangyubo I'm fine about it, please give me instructions what to do

**Comment by AlvaroLQueiroz** [comment]
@theromis version 1.3 is already available in pypi.
