### ISSUE TITLE
The field data of Notification returns NULL

### ISSUE THREAD

**Issue by Shashankagarwal181996** [django-notifications/django-notifications#175]
Whenever something is stored in the field data of Notification model, it is not saved or properly stored i.e. when the the field data of an instance of notification is accessed again,then it returns NULL/None always. I do have a fix which I applied , so may I submit a pull request.

**Comment by Shashankagarwal181996** [comment]
@yangyubo  , Could you tell me , if I can submit a pull request for this, or from whom can I ask about this ?

**Comment by yangyubo** [comment]
@Shashankagarwal181996 yes, please create a PR, thx!

**Comment by AlvaroLQueiroz** [comment]
@Shashankagarwal181996 did you define the 'NOTIFICATIONS_USE_JSONFIELD' variable inside the settings?

**Comment by Shashankagarwal181996** [comment]
@AlvaroLQueiroz No I did not use that but when I specified data in models.py with actor , verb etc in  function unicode of class Notification then it worked..
