### ISSUE TITLE
Question: Is the project supported on Django 1.11?

### ISSUE THREAD

**Issue by archatas** [django-notifications/django-notifications#181]
Hello, is the app supported on Django 1.11 and if not, what are the plans for that?

**Comment by feigenblatt** [comment]
Interested in this as well. 
Thanks.

**Comment by pablochud** [comment]
Same question
Thanks.

**Comment by tinyms** [comment]
the app supported on Django 1.11.5

**Comment by AlvaroLQueiroz** [comment]
I believe so, because all the tests are passing on Django 1.11. Any of you tested it?

**Comment by psychok7** [comment]
I am using 1.3 with Django 1.11.7 without any issues on production
