### ISSUE TITLE
Custom Signal from django.dispatch not working

### ISSUE THREAD

**Issue by fridary** [django-notifications/django-notifications#187]
I need to send notification and make it unread=False. I replaced `notify` variable to extend `providing_args`, but notifications are not sent (even if I remove `unread` arg).
I tried `notify.send_robust()` - the same results and don't know even how catch error or what happened
This code I placed in `views.py`:

```
from django.dispatch import Signal

notify = Signal(providing_args=[
    'recipient', 'actor', 'verb', 'action_object', 'target', 'description',
    'timestamp', 'level', 'unread'
])

s = notify.send(request.user, recipient=agency, verb='my_verb', target=project, unread=False)
# `s` is [] now
```

Django version: 1.11

**Comment by AlvaroLQueiroz** [comment]
You need to connect the signal to a callback function, by default __notify__ is connected in __notifications.models.notify_handler()__ function. And this functions not use the param _unread_, to solve your issue you need rewrite your own signal handler.
