### ISSUE TITLE
Documentation set up

### ISSUE THREAD

**Issue by Ashaba** [django-notifications/django-notifications#188]
I think there is a problem as regards documention especially on setting up and sending a notification.
For example ```notify.send()``` the said documentation suggests more than two parameters.

But after putting more than two or even less I get this error
- ```send() takes 2 positional arguments but 3 were given```

**Comment by AlvaroLQueiroz** [comment]
The __notify_send__ function only accepts two positional arguments, _actor_ and _verb_. To pass more than this two arguments you need use named arguments, like this:
```python
notify.send(actor=user, verb='created a issue', recipient=User.objects.all()) 
````
