### ISSUE TITLE
KeyError: 'recipient'

### ISSUE THREAD

**Issue by zeleven** [django-notifications/django-notifications#189]
Why I get this error?
I install the package, add the app in my `INSTALLED_APPS` and migrate the database. According to the project readme, I add the code in my `models.py`:
```python
from django.db.models.signals import post_save
from notifications.signals import notify
def my_handler(sender, instance, created, **kwargs):
    notify.send(instance, verb='created topic success')


post_save.connect(my_handler, sender=Topic)
```
After that, I run my project, and I got the error: `KeyError: 'recipient'`

**Comment by AlvaroLQueiroz** [comment]
You need to pass the __recipients__ that will receive the notification.
