### ISSUE TITLE
ReferenceError: register_notifier is not defined

### ISSUE THREAD

**Issue by SergenTdln** [django-notifications/django-notifications#190]
_First of all, thank you for your work !_ 

While trying tu use {% live_notify_list %} i get that error. 

here is what is load by the js: 

<ul id='live_notify_list' class='dropdown-menu'></ul>
        <script>
        notify_badge_id='live_notify_badge';
        notify_menu_id='live_notify_list';
        notify_api_url='/inbox/notifications/api/unread_list/';
        notify_fetch_count='5';
        notify_unread_url='/inbox/notifications/unread/';
        notify_mark_all_unread_url='/inbox/notifications/mark-all-as-read/';
        notify_refresh_period=15000;
    register_notifier(fill_notification_list);register_notifier(fill_notification_badge);</script>

Any ideas ? thank you

**Comment by AlvaroLQueiroz** [comment]
You loads the [notification.js](https://github.com/django-notifications/django-notifications/blob/master/notifications/static/notifications/notify.js) file before using _{% live notify_list %}_?
