### ISSUE TITLE
Not a directory: '/usr/local/lib/python2.7/dist-packages/django_notifications_hq-1.3-py2.7.egg/notifications/migrations'

### ISSUE THREAD

**Issue by yulstewartgurrea** [django-notifications/django-notifications#191]
Im getting this error when i try to put 'notifications' in my installed apps:

Not a directory: '/usr/local/lib/python2.7/dist-packages/django_notifications_hq-1.3-py2.7.egg/notifications/migrations'

**Comment by AlvaroLQueiroz** [comment]
Weird!! Try reinstall the django-notifications again. If the problem persist, send us more info about your code and problem.

**Comment by yulstewartgurrea** [comment]
So the error occurs when i try to upgrade django to 2.0. Im using 1.11.5 right now and its working ok..

**Comment by arpang** [comment]
I am getting the same error with Django 2.0. Any help?

**Comment by yulstewartgurrea** [comment]
I downgraded my version since we were using 1.11 at the time.

**Comment by arpang** [comment]
Thanks!

**Comment by airosk** [comment]
This [pull request](https://github.com/django-notifications/django-notifications/pull/211) fixes the issue
