### ISSUE TITLE
Notify All Staff - Getting it to work

### ISSUE THREAD

**Issue by bobozar** [django-notifications/django-notifications#192]
How do I go about sending notifications to all staff when a user sends a message. I want to notify all staff. So I will need to add more than one user to the 'recipient'. 

How do I add more than one recipient?

**Comment by AlvaroLQueiroz** [comment]
Just pass __User.objects.filter(is_staff=True, is_active=True)__ for the _recipient_ param.

**Comment by bobozar** [comment]
Thanks bro. Will try it out.
