### ISSUE TITLE
how to use url('^inbox/notifications/', include(notifications.urls, namespace='notifications'))?

### ISSUE THREAD

**Issue by SamsadSajid** [django-notifications/django-notifications#197]
As mentioned in the **README** section, I added `url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),` in the `url.py`.
Now in my html, I have an icon for notification bell. I am using a `href` in the icon. It looks like this:
`<a href="{% url 'notification:all' %}" id="notifications" title="Notification">`
It takes me to a html which I did not write. It's a plain html page. How may I able to configure it by my own?

**Comment by AlvaroLQueiroz** [comment]
You have two option.
The first one is, write your own view, and point the anchor to it and not to __'notification:all'__.
The second way is override the default templates. To do it, create the files __templates/notifications/list.html__ and __templates/notifications/notice.html__.

**Comment by SamsadSajid** [comment]
And where should I put it?
```
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
```
where I am writing all my script tags, i.e
<script src="{% static 'css/bootstrap.min.css' %}" type="text/javascript"></script>
that would be in the bottom part of my html.
If so then, adding this: 
`{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}`
would work? 
And also what would it do if I only write
`{% register_notify_callbacks' %}`
And is it possible to show a list of notification just like facebook does, expand the list while clicking/hovering the bell?(I have already commented the related problem I faced in issue#198)
