### ISSUE TITLE
Bootstrap {% live_notify_list classes="dropdown-menu" %} error

### ISSUE THREAD

**Issue by davidkrcil** [django-notifications/django-notifications#198]
When I use syntax for Bootstrap:  {% live_notify_list classes="dropdown-menu" %} I got Error:

Request Method: | GET
-- | --
http://127.0.0.1:8000/en/fastsearch/map/
1.8.18
TemplateSyntaxError
'live_notify_badge' received unexpected keyword argument 'classes'
/virtualenv/lib/python2.7/site-packages/django/template/base.py in parse_bits, line 1048
/virtualenv/bin/python
2.7.12
['/app',  '/virtualenv/lib/python27.zip',  '/virtualenv/lib/python2.7',  '/virtualenv/lib/python2.7/plat-linux2',  '/virtualenv/lib/python2.7/lib-tk',  '/virtualenv/lib/python2.7/lib-old',  '/virtualenv/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7',  '/usr/local/lib/python2.7/plat-linux2',  '/usr/local/lib/python2.7/lib-tk',  '/virtualenv/lib/python2.7/site-packages',  '/virtualenv/lib/python2.7/site-packages/django_notifications_hq-1.3-py2.7.egg',  '/virtualenv/lib/python2.7/site-packages/pytz-2017.3-py2.7.egg',  '/virtualenv/lib/python2.7/site-packages/jsonfield-2.0.2-py2.7.egg',  '/virtualenv/lib/python2.7/site-packages/django_model_utils-3.0.0-py2.7.egg']

**Comment by AlvaroLQueiroz** [comment]
Sorry about that, the documentation is outdated. The right argument is **list_class**. The correct way to use  is: __{% live_notify_list list_class="dropdown-menu" %}__

**Comment by SamsadSajid** [comment]
I used this:
`{% live_notify_list list_class="dropdown-menu" %}`
and I'm getting this error:

> Request Method: | GET
> -- | --
> http://127.0.0.1:8000/production/notification
> 1.11.6
> TemplateSyntaxError
> 'live_notify_list' received unexpected keyword argument 'list_class'

**Comment by davidkrcil** [comment]
@AlvaroLQueiroz thank you for fast reply. 

I have no problem as @SamsadSajid but when I use: {% live_notify_list list_class="dropdown-menu" %}

But I am getting empty <ul class="dropdown-menu"></ul> with no notifications

To get existing notification I have to use only {% live_notify_list %}

I am using django-bootstrap3 to provide all required

Please would you have a hint what I am doing in wrong way?
Thank you
David

**Comment by davidkrcil** [comment]
Resloved - I added dropdown markup in template manually 
` <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Notifs {% live_notify_badge %} <span class="glyphicon glyphicon-user pull-right"></span></a>
          <ul class="dropdown-menu">

          </ul>
        </li>
      </ul>`

and registered 

{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge'  menu_class="dropdown-menu" %}

than  {% live_notify_list list_class="dropdown-menu" %} works fine

@AlvaroLQueiroz big thanks

**Comment by Kypaz** [comment]
The doc is outdated .. it should be {% live_notify_list classes='dropdown-menu' %} .. I had to check on the code of the notifications module installed in my venv .. The version of django-notifications available through pip is not the same as this repo

**Comment by SamsadSajid** [comment]
@davidkrcil 
`{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' menu_class="dropdown-menu" %}`
Here, is `menu_class` your custom tag?
And also where did you put this:
`{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' menu_class="dropdown-menu" %}`
and this:
`{% live_notify_list list_class="dropdown-menu" %}`
and this:
`<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>`
I still could not make it work!!!

**Comment by davidkrcil** [comment]
@SamsadSajid start with this:

{% load notifications_tags %} {% load static %}

than prepare for dropdown:

`<ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Notifs {% live_notify_badge %} <span class="glyphicon glyphicon-user pull-right"></span></a>
          <ul class="dropdown-menu dropdown-menux">

          </ul>
        </li>
      </ul>`


and than register call-backs


<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' fetch=22 menu_class="dropdown-menux" %}

menu_class is parameter of register_notify_callbacks callbacks

now just call: {% live_notify_list list_class="dropdown-menu" %}

It works for me

It is needed to have bootstrap and jquery in page - I have used django-bootstrap3 and because of it I have in between of HEAD of template this:

{# Load the tag library #}
    {% load bootstrap3 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

let know if that helped

**Comment by surfer190** [comment]
Sorry is this resolved?
My bootstrap js is at the end of the page:

I add these in the `navbar`:

```
{% live_notify_badge badge_class="badge" %}
{% live_notify_list list_class="dropdown-menu" %}
```

Loading static:

`{% load bootstrap3 static notifications_tags %}`

Bottom of the page scripts:

```
{% bootstrap_javascript  jquery=1 %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
```

I get this error:

`'live_notify_badge' received unexpected keyword argument 'badge_class'`

**Comment by SamsadSajid** [comment]
`{% live_notify_badge classes="badge" %}` this worked for me

**Comment by surfer190** [comment]
@SamsadSajid Yeah but that is contrary to the documentation. I think this error is happening because installing from pip and installing from source are different versions

**Comment by SamsadSajid** [comment]
Yeah, I almost forgot there's an issue about the installation. You're right.
