### ISSUE TITLE
Abstract base models

### ISSUE THREAD

**Issue by nemesisdesign** [django-notifications/django-notifications#202]
I would like to use this app as a base in an open source project called @openwisp.

Would abstract base (extensible) models be an interesting feature for the maintainers of this project?

I did [something similar for django-organizations](https://github.com/bennylope/django-organizations/pull/119) a while ago.

Cheers!

**Comment by nemesisdesign** [comment]
@AlvaroLQueiroz, @LegoStormtroopr, @yangyubo, @zhang-z, what do you think?

**Comment by knno** [comment]
Thanks for contributing, I hope to see this works out : )

**Comment by nemesisdesign** [comment]
Done in #255.
