### ISSUE TITLE
Django-notification delete API from front-end

### ISSUE THREAD

**Issue by imran-hassan** [django-notifications/django-notifications#203]
Can you please help me about django-notification??? I am able to implement it, but stuck in delete from front end using this API 
delete/(?P\d+)/
what I suppose to provide in place of (?P\d+)/ , when I call this API
There is no "slug" key in object I receive on front end

**Comment by AlvaroLQueiroz** [comment]
The slug is a "hash" of id object. You can calculate this "hash" on your frontend and send to API. [This](https://github.com/django-notifications/django-notifications/blob/master/notifications/utils.py) is where the slug is calculated.

**Comment by Samoht1** [comment]
yae but how do you use the util in the frontend?
