### ISSUE TITLE
Passing the `timesince()` format to the live-updater instead of ISO8601

### ISSUE THREAD

**Issue by simonsterj** [django-notifications/django-notifications#204]
How can it be done?  

attempting to pass a timezone aware `'timesince': self.timesince(now=datetime.datetime.now(timezone.utc))`  time into the string representation of the object does not seem to work. Any idea to switch out the ISO8601 into a more human-readable timestamp to be displayed on the live-updater?

**Comment by AlvaroLQueiroz** [comment]
You need set `USE_TZ = True` in your project setting.

**Comment by rocchidavide** [comment]
I don't understand: should /inbox/notifications/api/unread_list/ URL return timesince value for every unread_list item? I need to have in JS timesince
