### ISSUE TITLE
How to fetch all notifications for an action

### ISSUE THREAD

**Issue by nishitchittora** [django-notifications/django-notifications#205]
I want to show all notifications (read and unread) for an actor. There is one way which via a url '/indox/notifications' but that redirect to its custom template.  There is no django rest api for this work.

**Comment by AlvaroLQueiroz** [comment]
We do not currently support this feature. You will need to write your own view (PR are welcome).

**Comment by cavinblake** [comment]
> We do not currently support this feature. You will need to write your own view (PR are welcome).

Sir, can you help me with the action object and target in the notifications. There is not much in the docs to fully understand.
