### ISSUE TITLE
Notifications for a proxy model

### ISSUE THREAD

**Issue by msi2** [django-notifications/django-notifications#206]
Hi,

In the case of an actor based on a proxy model, the content type saved is the content type of the base model.

Is there any standard way to bypass this behaviour ?

Thanks

**Comment by msi2** [comment]
By changing the line 281 (branch 1.3) below in `models.py`, it saves the right content type :

from
`actor_content_type=ContentType.objects.get_for_model(actor),`
to
`actor_content_type=ContentType.objects.get_for_model(actor, False),`

**Comment by ziXet** [comment]
can you please create a PR for this fix?

**Comment by AlvaroLQueiroz** [comment]
Fixed on #320
