### ISSUE TITLE
best way to impliment django notification system in my app

### ISSUE THREAD

**Issue by rahul6612** [django-notifications/django-notifications#209]
i created a app where peoples can like/unlike posts they can follow/unfollow  to each other and my question is:
1. when **user A** like/unlike **user B** posts, **user B** get the notification (**user A** liked/unliked your post)
2. when **user A** follow **user B**,  **user B** get the notification(**user A** follow you)
3. i have no idea about it so which is the best way to implement it.
4. notification system shoult be fast and roboust means its should show without reloading the page

any idea

**Comment by zmrenwu** [comment]
Maybe you can use Vue or React.

**Comment by AlvaroLQueiroz** [comment]
You will need use some front end lib (like React, Angular or Vue) or just use AJAX.
