### ISSUE TITLE
can not use with django 2

### ISSUE THREAD

**Issue by anuj9196** [django-notifications/django-notifications#213]
I have installed version 1.3 in Django 2.0

But it is giving error as
```
class Notification(models.Model):
  File "/Users/anuj/.local/share/virtualenvs/src-UhWPeMJs/lib/python3.6/site-packages/notifications/models.py", line 170, in Notification
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, related_name='notifications')
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by thunderwin** [comment]
I have the same issue, says

`    TypeError: __init__() missing 1 required positional argument: 'on_delete'
`

**Comment by udos** [comment]
from https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0:

> The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations.

this should affect everyone who uses or upgrades to Django 2.x...
note: relates to #212 (I'm also waiting for a fix to give it a try...)

**Comment by shivam2146** [comment]
this issue arise if using django 2.0 and installing django notifications using pip.
installing from github using python setup.py install fixes this issue(but req some fix in setup.py file refer https://github.com/django-notifications/django-notifications/pull/211 for fix).

**Comment by anuj9196** [comment]
It seems the pip repository is not up to date. The developer must draft a new release in pip repository.
I can't install it from git as my project has the remote team and many developers are working on it. I need to ask them all to follow the tedious task.

**Comment by rrluthi** [comment]
This is affecting me as well, seems like the pip repo needs to be updated. The suggested approach is fine for one-offs, but frustrating and tedious.

**Comment by AlvaroLQueiroz** [comment]
A new version is already on PYPI.
