### ISSUE TITLE
I am not able to use Djano notifications, i.e. generating notifications module

### ISSUE THREAD

**Issue by ssridhar2065** [django-notifications/django-notifications#214]
Hi Authors,
Sorry about this, but I am really unable to embed this generate notifications into my project.

I want a simple example code program, take Hello world program and embed this generate notifications.

Can you please help me with reference code?

**Comment by AlvaroLQueiroz** [comment]
[Here](https://github.com/django-notifications/django-notifications/tree/master/notifications/tests) you can see a really simple exemple of how to use the lib.
