### ISSUE TITLE
I find some problem just like 【warnerror3】can not find site-packages/django_notifications_hq-1.4.0a0-py3.6.egg/notifications/migrations

### ISSUE THREAD

**Issue by nejinn** [django-notifications/django-notifications#215]
IF you have this problem，you can do this：
**my django==2.0** 
1.git clone https://github.com/django-notifications/django-notifications
cd django-notifications
python setup.py install
2. go to \Python36\Lib\site-packages
3.creat a folder named **django_notifications_hq-1.4.0a0-py3.6.egg** ，before this action，you must delete file named **django_notifications_hq-1.4.0a0-py3.6.egg**
4.  Back to step 1
find and open the folder named django-notifications
my django-notifications folder path is C:\Users\Administrator\django-notifications
![image](https://user-images.githubusercontent.com/31615794/40537368-5716ce74-6041-11e8-997a-d1563e82cb06.png)
5. open folder named **django_notifications_hq.egg-info**
copy all files into the folder we creat in step 3
![image](https://user-images.githubusercontent.com/31615794/40537400-66494426-6041-11e8-90ab-c3039cda81e6.png)
![image](https://user-images.githubusercontent.com/31615794/40537417-7176c8be-6041-11e8-930f-f751fac6a220.png)
6. copy the folder named **notifications**  into **\Python36\Lib\site-packages**
![image](https://user-images.githubusercontent.com/31615794/40537500-a2fe514a-6041-11e8-9ff4-53c11777969b.png)
![image](https://user-images.githubusercontent.com/31615794/40537510-ad6eb0c0-6041-11e8-89bd-99f9a44f0d2c.png)

OK，you can enjoy your work

PS:
https://github.com/django-notifications/django-notifications/pull/211 
The way in this can not solve my problem，it doesn't work

**Comment by nejinn** [comment]
@AlvaroLQueiroz 
why closed my issues？
this some problem when pip install django-notifications-hq
I can not find the folder notifications in **Python36\Lib\site-packages**
there is not folder
In my site-packages have not notifications

**Comment by AlvaroLQueiroz** [comment]
Did you try to reinstall? Version 1.4 is in PYPI now.

If you need install from repo, just follow the steps:
1. git clone https://github.com/django-notifications/django-notifications
2. cd django-notifications
3. python setup.py sdist
4. pip install dist/django-notifications-hq*
