### ISSUE TITLE
KeyError: `USE_JSONFIELD`

### ISSUE THREAD

**Issue by sciyoshi** [django-notifications/django-notifications#218]
Getting this error since the latest changes. Looks like maybe the default config needs to be updated here: https://github.com/django-notifications/django-notifications/blob/master/notifications/settings.py#L6

```
  File "/home/circleci/venv/src/django-notifications-hq/notifications/models.py", line 240, in <module>
    EXTRA_DATA = notifications_settings.get_config()['USE_JSONFIELD']
KeyError: 'USE_JSONFIELD'
```

**Comment by AlvaroLQueiroz** [comment]
@sciyoshi thanks.
