### ISSUE TITLE
Object of type 'User' is not JSON serializable

### ISSUE THREAD

**Issue by kanikadhiman17** [django-notifications/django-notifications#225]
Following are my current settings:
CONFIG_DEFAULTS = {
    'PAGINATE_BY': 20,
    'USE_JSONFIELD': True,
    'SOFT_DELETE': False,
}

This is how i am using the function:
notify.send(sender=request.user, actor=request.user, recipient=request.user,
						verb='You left the ', target=community, comm_url="community_view")

I am getting this error : 
Object of type 'User' is not JSON serializable

Please help me out!

**Comment by AlvaroLQueiroz** [comment]
In yours settings.py you need set:

```python
DJANGO_NOTIFICATIONS_CONFIG = {
    'USER': True
}
```

**Comment by kanikadhiman17** [comment]
Already tried it..  Getting the same error again!

**Comment by AlvaroLQueiroz** [comment]
Sorry, my bad. The docs in the repo is in front of the PYPI version.

In the version 1.4.0 the correct settings is:
```python
NOTIFICATIONS_USE_JSONFIELD = True
```
And NOT equal my last comment.

**Comment by Janice-M** [comment]
I think user is not serializeable because we are using the django user with all its fields.
