### ISSUE TITLE
I can not get the object list with "live-updater with bootstrap"

### ISSUE THREAD

**Issue by mezitax** [django-notifications/django-notifications#226]
Hi guys, the notification live-updater works fine for me but
when i use the live-updater with bootstrap in the template
`{% live_notify_list list_class="dropdown-menu" %}`
the list of objects is not refreshed
![with change template](https://user-images.githubusercontent.com/1774655/41186329-974b3ad0-6b62-11e8-8e87-2fed21e053f4.jpg)
but when I use it by default, I can get the list of objects.
![without change template](https://user-images.githubusercontent.com/1774655/41186447-b4e18124-6b64-11e8-8824-b5a2e2397c52.jpg)
The only way that works for me is modifying the two lines of the file notifications_tags.py
```
def register_notify_callbacks (badge_class = 'live_notify_badge',
                               menu_class = 'dropdown-menu',
```

```
@ register.simple_tag
def live_notify_list (list_class = 'dropdown-menu'):
```
and works
![with change notifications_tags-py](https://user-images.githubusercontent.com/1774655/41186330-977eee98-6b62-11e8-9654-b33489a2c3c8.jpg)

*and another thing, is there any way to get the live-updater with more css in the < li > ?, I liked the result that I get with the static list, maybe use the template list.html for the live-updater?

**Comment by AlvaroLQueiroz** [comment]
You need to do this:

your_file.html
```html
// Register the functions that you need and set de classes for the container where data is append.
{% register_notify_callbacks callbacks='fill_notification_list' menu_class='dropdown-menu' %}

<a href="#" class="dropdown-toggle" data-toggle="dropdown" >...</a>
<ul class="dropdown-meny"></ul>
```

For get LI`s more stylized, you can write your own JS function for fill the container pointed by __menu_class__ parameter. And  replace __fill_notification_list__ in __register_notify_callbacks__ by your function.

**Comment by mezitax** [comment]
-but that replaces all my "dropdown-menu"

-As for the style thanks, the .js was the only file I was missing for reviewing: D, I will stylize my menu there

**Comment by AlvaroLQueiroz** [comment]
To not replace all dropdown-menu, add some more class to __menu_class__ and the __ul__:

**Comment by mezitax** [comment]
thanks
