### ISSUE TITLE
Wrong documentation about extra data?

### ISSUE THREAD

**Issue by rocchidavide** [django-notifications/django-notifications#227]
In docs you said:

> Add to your settings.py: DJANGO_NOTIFICATIONS_CONFIG = { 'USE_JSONFIELD': True}

But extra data not working. Taking a look to the source code I see that instead should be used (and so it works):

NOTIFICATIONS_USE_JSONFIELD = True

Django==1.11.7
django-notifications-hq==1.4.0

**Comment by kanikadhiman17** [comment]
in mine, it's still not working. Did you change settings.py file of django-notifications? Or some other recommendations?

Django==1.11.7
django-notifications-hq==1.4.0

**Comment by AlvaroLQueiroz** [comment]
Sorry, my bad. The docs in the repo is in front of the PYPI version.

In the version __1.4.0__ the correct settings is: __NOTIFICATIONS_USE_JSONFIELD = True__

**Comment by lainor** [comment]
+1, please update the README

**Comment by R-o-y** [comment]
+1

**Comment by AlvaroLQueiroz** [comment]
New version released in pypi.
