### ISSUE TITLE
Can actor_object_id be non-numeric character?

### ISSUE THREAD

**Issue by SirSaleh** [django-notifications/django-notifications#231]
Based on my question in [stackoverflow](https://stackoverflow.com/questions/51129487/django-notification-invalid-literal-for-int-with-base-10?noredirect=1#comment89245043_51129487) Isn't it better to `actor_object_id` in [models](https://github.com/django-notifications/django-notifications/blob/master/notifications/models.py) be IntegerField?

**Comment by AlvaroLQueiroz** [comment]
The __actor_object_id__ needs to be a __CharField__ to support __UUID__ based primary keys.
