### ISSUE TITLE
Human readable date/time instead of TZ

### ISSUE THREAD

**Issue by jdhurwitz** [django-notifications/django-notifications#233]
Is there a way to configure the notification so that the date/time is displayed in a human readable format instead of a TZ object? Here is what it looks like now:

![image](https://user-images.githubusercontent.com/9702107/43162407-bd9ae07c-8f3f-11e8-964f-c5c2987df2b0.png)

**Comment by kaiofreitas** [comment]
It would be nice a integration with django-humanize.
I've been trying to figure it out, but unsuccessful.
