### ISSUE TITLE
Incorrect settings on Release Note for 1.5.0

### ISSUE THREAD

**Issue by pandabearcoder** [django-notifications/django-notifications#235]
What's posted is `DJANGO_NOTIFICATION_CONFIG = {`

Instead of `DJANGO_NOTIFICATIONS_CONFIG = {`

**Comment by henrinie** [comment]
Noticed the same. Which one is correct?
Also the rst syntax is a little off.

**Comment by nemesisdesign** [comment]
@pandabearcoder @henrinie send a patch if you can please, thanks for contributing.
