### ISSUE TITLE
Version error if using Django RC version 

### ISSUE THREAD

**Issue by mishu-** [django-notifications/django-notifications#236]
In my requirements.txt file I tried using: `Django==2.1rc1`
`django-notifications` throws out this error:
```
File "lib/python3.6/site-packages/notifications/models.py", line 21, in <module>
    if StrictVersion(get_version()) >= StrictVersion('1.8.0'):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '2.1rc1'
```

**Comment by sv0** [comment]
Accordingly to distutils.version.StrictVersion, "2.1rc1" is an invalid version number:


    class StrictVersion (Version):
    
        """Version numbering for anal retentives and software idealists.
        Implements the standard interface for version number classes as
        described above.  A version number consists of two or three
        dot-separated numeric components, with an optional "pre-release" tag
        on the end.  The pre-release tag consists of the letter 'a' or 'b'
        followed by a number.  If the numeric components of two version
        numbers are equal, then one with a pre-release tag will always
        be deemed earlier (lesser) than one without.

        The following are valid version numbers (shown in the order that
        would be obtained by sorting according to the supplied cmp function):

            0.4       0.4.0  (these two are equivalent)
            0.4.1
            0.5a1
            0.5b3
            0.5
            0.9.6
            1.0
            1.0.4a3
            1.0.4b1
            1.0.4

        The following are examples of invalid version numbers:

            1
            2.7.2.2
            1.3.a4
            1.3pl1
            1.3c4

**Comment by mishu-** [comment]
Yes, this means that I am limited in using only final releases and a/b versions of django with this plugin. I had to downgrade django in order to get a package to work. It doesn't seem like it's the way to go. Pip likes it, django-notifications doesn't.

**Comment by AlvaroLQueiroz** [comment]
We already dropped support for Django < 3.2
