### ISSUE TITLE
How can I handle notifications when the user to which the notification gets deleted.

### ISSUE THREAD

**Issue by ravitdx** [django-notifications/django-notifications#237]
Hi,

I am using django==1.8.19 and django-notifications-hq==1.0. I had to remove few users from back-end. But, When I am trying to do so, I am getting an error saying `update or delete on table "auth_user" violates foreign key constraint "notification_noticesetting_user_id_fkey"`. How can I handle this problem. How can I make such a way that, when I remove a user, notifications regarding that user should also be removed.
Please help me out. thanks.

**Comment by AlvaroLQueiroz** [comment]
This was already fixed and we have dropped the support for Django < 3.2. But in this case you can filter and delete all notifications for these users before deleting them.
