### ISSUE TITLE
Used as Push Notifications, Possible?

### ISSUE THREAD

**Issue by bobozar** [django-notifications/django-notifications#238]
Just a quick one. Can django-notifications be used for push notifications on mobile devices?

**Comment by AlvaroLQueiroz** [comment]
Hi @bobozar, unfortunately this lib doesn't work this way.

**Comment by morenoh149** [comment]
PN is something your api needs to trigger against apple APN or google firebase. You could have a Django-notification and have the creation of a notification also trigger a PN. But that is something you add on top of this lib. Please close this issue.

**Comment by Flimm** [comment]
I would like just like to clarify, there are two separate features:

- the ability of the browser to display a notification outside of the normal window, the same way a normal application does, this is called Web Notifications [caniuse](https://caniuse.com/#feat=notifications)
- the ability the send notifications even when the browser hasn't got the website open. This is called Web Push [caniuse](https://caniuse.com/#feat=push-api).

It is possible to implement the former without Apple's APN or Google or Mozilla's push endpoints.

**Comment by morenoh149** [comment]
> Can django-notifications be used for push notifications on mobile devices?
I think this introduces a third scenario. Push notifications on a phone app through apn or gcm. The term push notification is ambiguous here. Then there are Progressive webapps too :)
