### ISSUE TITLE
{% live_notify_list list_class="dropdown-menu" %} does not work

### ISSUE THREAD

**Issue by sebastianjungels** [django-notifications/django-notifications#243]
Hi, I tried all of the things I could find to make this work, but the list does not show. I can get the badge to show but not the list. Are there any ideas?

I am using django-bootstrap4. 

Thanks
Sebastian

**Comment by fox0571** [comment]
I've got the same issue.

**Comment by sebastianjungels** [comment]
Anyone?

**Comment by antoarva** [comment]
I've got exactly the same issue

**Comment by benjordanstanford** [comment]
Hi guys,
I've got the same issue, though, this helped me:

In site-packages/notifications/templatetags/notifications_tags.py I found the function live_notify_list:

I converted this function to the following:

`@register.simple_tag(takes_context=True)
def live_notify_badge(context, badge_class='live_notify_badge'):
    user = user_context(context)
    if not user:
        return ''

    html = "<span class='{badge_class}'>{unread}</span>".format(
        badge_class=badge_class, unread=user.notifications.unread().count()
    )
    return format_html(html)`

Now when I call `{% live_notify_list %}` within a template, I see at least a list of every notification entry. But I don't think refreshing is working like this.

**Comment by benjordanstanford** [comment]
Oh, well, now I realized from the post in the foreign language by Antoarva that there are alternatives like 
https://github.com/pinax/pinax-notifications#installation
or:
https://github.com/alireza-molaee/django-webline-notifications
for this, so I'll use this probably.

**Comment by rslider00** [comment]
If anyone is still having this issue, change "{% live_notify_list list_class="dropdown-menu" %}" to "{% live_notify_list list_class="live_notify_list dropdown-menu" %}.

The reason for this error is because the notify.js is specifically looking for a ul with the class "live_notify_list" so that it can populate the list. The documentation mentions that the non-bootstrap default example has no list_class and therefore uses the "live_notify_list" class as default; however, the example it provides for the bootstrap implementation is incorrect.

**Comment by vmisiko** [comment]
i have tried all the options but with no success until now, only {% live_notification_badge %} works, but the {% live_notify_list list_class="live_notify_list dropdown-menu" %}, does not work.

**Comment by Lucianod28** [comment]
I also have this issue, on the page it creates a `<ul>` with the proper classes but it's empty.

**Comment by jerrypaulsam** [comment]
Has anyone fixed this issue?

**Comment by ifranco14** [comment]
Same issue here. Adding the `live_notify_list` class didn't work too.

**Comment by linhnvhicts** [comment]
Are there still no solution for this? the document need to be updated on how to use this...

**Comment by goromachine** [comment]
> If anyone is still having this issue, change "{% live_notify_list list_class="dropdown-menu" %}" to "{% live_notify_list list_class="live_notify_list dropdown-menu" %}.
> 
> The reason for this error is because the notify.js is specifically looking for a ul with the class "live_notify_list" so that it can populate the list. The documentation mentions that the non-bootstrap default example has no list_class and therefore uses the "live_notify_list" class as default; however, the example it provides for the bootstrap implementation is incorrect.

and also to have the badge working live you have to add: `{% live_notify_badge badge_class="live_notify_badge badge over-icon-notification" %}`

This must be updated to the docs because is important.

**Comment by goromachine** [comment]
Also, the date is not working as if using the `notification.timestamp|timesince` django templatetag, so it shows the complete date. It just look wrong... If I try to hardcode a function then I have a problem with translations because is using JS and not Django directly... any Idea on that?

**Comment by MiloshWEST** [comment]
Same issue here, seems like the issue is related to XMLHttpRequest responseText that should be parsed to JSON. In particular notify.js file on line 58. The JONSparse can not parse responseText out of the blue, an escape for certain characters needs to be made I think.

**Comment by AlvaroLQueiroz** [comment]
There are two different problems here:

1 - The first one is about usage. When the **css class** from `{% live_notify_badge %}` and `{% live_notify_list %}`is changed, you need change to the same classes in `{% register_notify_callbacks %}`
Ex.:
```html
{% load static notifications_tags %}

<script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
<script src="{% static 'notifications/live-test.js' %}" type="text/javascript"></script>

{% register_notify_callbacks badge_class='MY-NEW-BADGE-CLASS' menu_class='MY-NEW-LIST-CLASS'  callbacks='fill_notification_list,fill_notification_badge'%}

<h1>Notification count</h1>
{% live_notify_badge badge_class='MY-NEW-BADGE-CLASS' %}

<h1>Notification list</h1>
{% live_notify_list list_class='MY-NEW-LIST-CLASS' %}
```

2 - The second one it's a bug [here](https://github.com/django-notifications/django-notifications/blob/70897b0e6d6d315c59fd423c6a912be371cb3159/notifications/templatetags/notifications_tags.py#L84).  When we are mounting the constants with the config, we are not transforming from Python boolean to JS boolean.
