### ISSUE TITLE
Consider removing the dependency on django-model-utils

### ISSUE THREAD

**Issue by tdruez** [django-notifications/django-notifications#244]
`django-model-utils` is only used in one place: https://github.com/django-notifications/django-notifications/blob/51677dd83654eb1f457612f1d4e04f20e59ee89a/notifications/models.py#L16

This could easily be replaced by a simple tuple https://docs.djangoproject.com/en/2.1/ref/models/fields/#choices

It seems overkill to depend on a thirdparty library for this.

Also, parts of the README like https://github.com/django-notifications/django-notifications/blob/master/README.rst#queryset-methods suggest that `django-model-utils` is required for QuerySet operations while it's not.

Cheers!

**Comment by morenoh149** [comment]
sounds like a great first PR!

**Comment by kyleturner** [comment]
Any traction here, @tdruez? Looking to integrate with `django-notifications` and love the idea of not pulling in another dependency... thanks!

**Comment by LegoStormtroopr** [comment]
Will investigate this, this week.

**Comment by tdruez** [comment]
PR submitted as https://github.com/django-notifications/django-notifications/pull/267

**Comment by AlvaroLQueiroz** [comment]
Fixed on [version 2](/django-notifications/django-notifications/tree/v2-alpha)
