### ISSUE TITLE
Is this project can implement in django rest framework

### ISSUE THREAD

**Issue by ajaiau0** [django-notifications/django-notifications#256]

**Comment by morenoh149** [comment]
yes Read https://github.com/django-notifications/django-notifications#serializing-the-django-notifications-model and close issue

**Comment by ajaiau0** [comment]
how the frontend  listen to the particular port,im using django rest and frontend angular.

**Comment by morenoh149** [comment]
@ajaiau0 the frontend doesn't typically listen to any port. That sounds like web sockets. A typical api will expose and endpoint `/notifications` that the frontend will query. Do not confuse this project with something like Push Notifications.
