### ISSUE TITLE
Problem with cached results after Django 2.2.5 update

### ISSUE THREAD

**Issue by alvarovelezgalvez** [django-notifications/django-notifications#265]
Hi there,

First of all thanks for the package, its really useful!

After a major update (to Python 3.7.3 and Django 2.2.5 from Python 2.7 and Django 1.11), we are facing some troubles with the update of the live bagde, as the api/unread_list/ is being cached and does not update properly. 

I have fixed it adding decorator: **django.views.decorators.cache.never_cache** to affected views (specially **live_unread_notification_list**). Maybe is a good idea to add a pull request.

Regards

**Comment by kyleturner** [comment]
@alvarovelezgalvez Any progress here on adding support for Django 2.2+? Would like to understand dependencies and limitations before we fully commit to integrating `django-notifications` into an enterprise app we're building. Thanks!

**Comment by alvarovelezgalvez** [comment]
Hi @kyleturner ,

I have commited a pull request with the fix i needed to have a working version of the package in the versions mentioned. Apart from this error i found, package was fully working for me.

Regards,
Álvaro.

**Comment by AlvaroLQueiroz** [comment]
We already dropped the support for Django < 3.2
