### ISSUE TITLE
Compatibility with Django 3.0

### ISSUE THREAD

**Issue by metteludwig** [django-notifications/django-notifications#269]
There are some issues with running django-notifications on Django 3.0

- Depends on django.utils.six (only in models.py)
- Depends on django-jsonfield which depends on django.utils.six
- Possibly more

Django-jsonfield is basically deprecated, especially since there will be a native json-field coming in Django 3.1.

**Comment by Siecje** [comment]
Do you have a link to the JSON field being added in Django 3.1?

**Comment by metteludwig** [comment]
> Do you have a link to the JSON field being added in Django 3.1?

See this PR: https://github.com/django/django/pull/11452

However, now that I'm reading it again I'm a bit uncertain if it really is scheduled for 3.1. I guess it's not actually complete yet?

**Comment by laymonage** [comment]
@metteludwig [It should](https://github.com/django/django/pull/11452#issuecomment-543850042)...

The implementation can be considered complete (and it has passed the tests), but the Django folks still need to review it again. Though it seems that they've been busy lately with the release of 3.0.

**Comment by nemesisdesign** [comment]
There's a replacement of django-jsonfields called jsonfield2 https://pypi.org/project/jsonfield2/

**Comment by Flimm** [comment]
@nemesisdesign Good call on `jsonfield2`. It does support Django 3.0, even though the PyPi page forgot to mention that. I don't know how easy it is to migrate from `Django-jsonfield` to `jsonfield2`. It might be better to just remove this dependency. Django 3.1 is only going to be released in August 2020.

**Comment by neowenshun** [comment]
Hello there , is there any updates on how to make this app compatible with django 3.0?

**Comment by jhurtadojerves** [comment]
I am interested in updating my project to django 3.0. In the test environment I updated it and this library gives errors for packages removed from the django 3 kernel.

**Comment by nemesisdesign** [comment]
Migrate to `jsonfield2` is easy because it's a fork of `jsonfield` which has been upgraded to django 3.

I think we should release a version on pypi now and then start working on the next version in which we have to drop support for python 2 and django versions older than 2.2.

But I don't have access to this package on pypi.

**Comment by Siecje** [comment]
Who can publish a release on PyPI? Is it time for a fork?

**Comment by Flimm** [comment]
While the work is being done on making this compatible with Django 3.0, could up update be made on PyPI, marking this package as incompatible with Django 3.0 in the metadata?

**Comment by Flimm** [comment]
`jsonfield` ([Pypi](https://pypi.org/project/jsonfield/), [Github](https://github.com/dmkoch/django-jsonfield)) has just released version 2.1.0 which supports Django 3.0. See [changelog](https://github.com/dmkoch/django-jsonfield/blob/master/CHANGES.rst). So we might not need to migrate away from it after all.

This project, `django-notifications`, depends on the Pypi package [`jsonfield`](https://pypi.org/project/jsonfield/). It does not depend on the Pypi package [`django-jsonfield`](https://pypi.org/project/django-jsonfield/), which is a different package. I think previous comments were confusing the two. See this comment in the description of `jsonfield`:

> Note: There are a couple of third-party add-on JSONFields for Django. This project is `django-jsonfield` here on GitHub but is named `jsonfield` on PyPI. There is another `django-jsonfield` on Bitbucket, but that one is `django-jsonfield` on PyPI. I realize this naming conflict is confusing and I am open to merging the two projects.

**Comment by nemesisdesign** [comment]
Should be solved: https://pypi.org/project/django-notifications-hq/1.6.0/

**Comment by Flimm** [comment]
It now works in Django 3.0! Thank you @nemesisdesign and @hamstap85 .
