### ISSUE TITLE
How to visually distinguish between list of all notifications and list of unread notifications?

### ISSUE THREAD

**Issue by Flimm** [django-notifications/django-notifications#275]
The URL to display all notifications and the URL to display only unread notifications both use the same template: `notifications/list.html`

This means that when the user loads a list of notifications, it looks identical in style, and the headings are the exact same, regardless of whether the list is filtered or not.

What is the best way to display to the user that the current list being displayed is in fact filtered?

**Comment by AlvaroLQueiroz** [comment]
The class `icon-mail-alt` is added to unread notifications [here](https://github.com/django-notifications/django-notifications/blob/cccade4c344da456caa681d20fb439da1d66158c/notifications/templates/notifications/notice.html#L7). And you can change this template to supply your needs.
