### ISSUE TITLE
how to use the action object and target to mapping the url of the post, comment and userprofiles?

### ISSUE THREAD

**Issue by BinaryShip** [django-notifications/django-notifications#277]
I've installed the notification and its working correctly , users get their notifications but what i can't do is to mapping the url. users have notifications but they can't interacting. I think the target and action object will give them the url for the particular posts notification, if anyone follows them they are notified and when they clicked the notification they can show the user by going to their userprofile id.
`@login_required
      def like_post(request):
   # posts = get_object_or_404(Post, id=request.POST.get('post_id'))
    posts = get_object_or_404(post, id=request.POST.get('id'))
     # posts.likes.add for the particular posts and the post_id for the post itself its belongs to the post 
     without any pk
     is_liked = False
         if posts.likes.filter(id=request.user.id).exists():
         posts.likes.remove(request.user)
     is_liked = False
     else:
         posts.likes.add(request.user)
    is_liked = True
    notify.send(request.user, recipient=posts.author, actor=request.user, verb='liked your post.', 
    target=posts )

    context = {'posts':posts, 'is_liked': is_liked, 'total_likes': posts.total_likes(),}

     if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})`

**Comment by shafay07** [comment]
@cavinblake what did u end up doing? I'm implementing something similar. Thanks!

**Comment by Chipop** [comment]
@shafay07 what did u end up doing? I'm implementing something similar. Thanks!

**Comment by bandarAlrooqi** [comment]
@gmverdon what did u end up doing? I'm implementing something similar. Thanks!

**Comment by AlvaroLQueiroz** [comment]
I'm not sure if I understand what you guys need, but if you want to redirect from a notification to the `action`, `target` or `sender` you can use `notification.action_object_url()`,`notification.target_object_url()` and `notification.actor_object_url()`
