### ISSUE TITLE
Swappable models

### ISSUE THREAD

**Issue by nemesisdesign** [django-notifications/django-notifications#281]
Implement swappable models using django-swappable.

**Comment by TheOneAboveAllTitan** [comment]
Working on it! :smile:

**Comment by TheOneAboveAllTitan** [comment]
@nemesisdesign I think it is already implemented for Notification model. Kindly have a look [here](https://github.com/django-notifications/django-notifications/blob/8dd1a5e82f2bf47511f2aa34f5d43df3ca545adc/notifications/models.py#L6)

**Comment by nemesisdesign** [comment]
Oh you're right @TheOneAboveAllTitan. 
I thought it was not implemented because it's not mentioned in the docs nor there are tests for it: https://github.com/django-notifications/django-notifications/tree/8dd1a5e82f2bf47511f2aa34f5d43df3ca545adc#abstractnotification-model
Can you help with that with an example in the README and the custom app tests like we do in OpenWISP?

Look for SAMPLE_APP here: https://github.com/openwisp/openwisp-ipam/pull/27/files
