### ISSUE TITLE
Use Django's bulk create to improve notifications creation performance

### ISSUE THREAD

**Issue by cbouvier15** [django-notifications/django-notifications#283]
Hi there! 👋 

I'm working on implementing a notifications sub-system for a project and because of that, I was analyzing in detail some parts of this great project.

So, when I saw the `notify_handler` method I noticed that, eventually, a bunch of notifications could be created and then saved within a `for` loop.

https://github.com/django-notifications/django-notifications/blob/8dd1a5e82f2bf47511f2aa34f5d43df3ca545adc/notifications/base/models.py#L285-L308

Do you guys think it would be possible to make use of [Django's bulk create](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#bulk-create) instead of calling save at every iteration?

I can work on it if you think it worth it.
Thanks!

**Comment by TheOneAboveAllTitan** [comment]
I doubt that this will be viable, from Django docs:

> The model’s save() method will not be called, and the pre_save and post_save signals will not be sent.

**Comment by AlvaroLQueiroz** [comment]
Fixed by 14f7651c35cf91c50dc068f4f067febe03fc7b19 in [V2](/django-notifications/django-notifications/tree/v2-alpha)
