### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "django_content_type" does not exist

### ISSUE THREAD

**Issue by samuelmovi** [django-notifications/django-notifications#292]
The issue's title is the error I get when attempting to migrate this app in project using Django 2.2.

After adding `django-notifications-hq==1.6.0` to requirements.txt, and `'notifications',` to settings.INSTALLED_APPS, I execute `python manage.py migrate`.
All other migrations work well, but not notifications.
Running `python manage.py showmigrations` shows:
```
...
notifications
 [ ] 0001_initial
 [ ] 0002_auto_20150224_1134
 [ ] 0003_notification_data
 [ ] 0004_auto_20150826_1508
 [ ] 0005_auto_20160504_1520
 [ ] 0006_indexes
 [ ] 0007_add_timestamp_index
 [ ] 0008_index_together_recipient_unread
...
```

Does anyonw else have this issue when trying to use the module?
Does it migrate well for everyone?
I'll say that I tried using django-activity-stream, which your project seems to be based on, and it throws the same error. However theirs only supports 1.x versions of Django.

I would appreciate any and all help in stomping this issue.
Thanx.

**Comment by AlvaroLQueiroz** [comment]
Have you found how to fix it?
