### ISSUE TITLE
live notify list does not populate for dropdown-menu

### ISSUE THREAD

**Issue by darahsten** [django-notifications/django-notifications#294]
The live_notify_list template tag does update with the actual notifications.

This is arising because the notify_menu_class is not populated [when it is called here](https://github.com/django-notifications/django-notifications/blob/master/notifications/static/notifications/notify.js#L21).

For this reason it results as an empty HTMLCollection object with length 0.

As a result of this, [this loop is never executed](https://github.com/django-notifications/django-notifications/blob/master/notifications/static/notifications/notify.js#L40) 

Consequently the html is not populated. And the drop down shows nothing. Even while the api is functional and running.

Perhaps we could consider initializing with [a variable here](https://github.com/django-notifications/django-notifications/blob/master/notifications/static/notifications/notify.js#L2).
`var notify_menu_class=live_notify_list` or dropdown-menu class.

Perhaps, I could also be educated as to why we are using an html class rather than an ID as though we should expect
notifications to be displayed in multiple places on the same page.

Using an ID would force a little bit of strictness. 
We could add the particular ID class in the live_notify_list template tag[ here](https://github.com/django-notifications/django-notifications/blob/master/notifications/templatetags/notifications_tags.py#L91)

```
@register.simple_tag
def live_notify_list(list_class='live_notify_list', notifications_id='notifications-id'):
    html = "<ul class='{list_class}' id='{notifications_id}'></ul>".format(
                    list_class=list_class, notifications_id=notifications_id)
    return format_html(html)
```
I guess the challenge I am not sure how to resolve here is how to tell the java script in a dynamic way what the ID to select is.
But I can do with a static id now.

**Comment by mascDriver** [comment]
i lost time with this problem but its simple case, you need specify the class you use and for more customize create new js, like:
HTML:
`{% register_notify_callbacks menu_class='list-group' callbacks='fill_notification_list, fill_notification_list_custom'  %}`
`{% live_notify_list list_class='list-group' %}`
JS:
```

function fill_notification_list_custom(data) {
    var menus = document.getElementsByClassName(notify_menu_class);
    if (menus) {
        var messages = data.unread_list.map(function (item) {
            var message = "";
            if(typeof item.verb !== 'undefined'){
                message = message + " " + item.verb;
            }
            if(typeof item.timestamp !== 'undefined'){
                message = message + " " + item.timestamp;
            }
            return '<a href="#"  class="list-group-item">' + message + '</a>';
        }).join('')

        for (var i = 0; i < menus.length; i++){
            menus[i].innerHTML = messages;
        }
    }
}
```

**Comment by AlvaroLQueiroz** [comment]
Duplicated with #243
