### ISSUE TITLE
All calls to django-notifications-hq api rest, return empty notify list after JWT authentication

### ISSUE THREAD

**Issue by mauroesposito** [django-notifications/django-notifications#295]
It's a very strange situation: I'm using django-notifications-hq in my app, and if I call the notifications list from model user, I can see all user notifications:

![image](https://user-images.githubusercontent.com/8039989/88403518-f6735f00-cdcc-11ea-9fa6-9276d65d38ba.png)

But when I made a call by Api rest, well, I can see that the result is ever empty:

![image](https://user-images.githubusercontent.com/8039989/88404180-d2fce400-cdcd-11ea-8320-ffba3cd2d404.png)

Debugging your `def live_all_notification_list(request):` I've noted that `request.user` is always an anonymous user.

Again: I've tryed to override your `live_all_notification_list` in mine `main.view()` (with a new url: `path("v1/notifications/unread_list/", main_views.live_all_notification_list)`, to avoid potential urls conflicts) and I've discovered that the problem is the decorator `@never_cache`, indeed, updating this decorator with a more generic `@api_view(["GET"])`, all work like a charm:

![image](https://user-images.githubusercontent.com/8039989/88404525-4a327800-cdce-11ea-8caa-fabaa0e16a92.png)

And last but not least, I've updated in your library view the decorator as `@api_view(["GET"])` instead of `@never_cache`, and this is the result:

![image](https://user-images.githubusercontent.com/8039989/88404917-d3e24580-cdce-11ea-9883-ba26e3d3049c.png)

All work fine, and the result is the same as view method override.

This may be a bug or exist a workaround to bypass this empasse?

Thank you guys for your work and for your help,
Mauro

**Comment by na0495** [comment]
you didn't include those changes in a pull request, to fix that issue when using drf & jwt ?

**Comment by KaizerJ** [comment]
With drf & token (knox token) authentication the initial behaviour happens too (have not tested the workaround)

**Comment by AlvaroLQueiroz** [comment]
I believe this is not a bug on this lib, because the `never_cache` and the `django-notifications` don't change the request, If the user is arriving as **Anonymous** some code before this is making this change, probably some middleware.
