### ISSUE TITLE
concatenate notifications

### ISSUE THREAD

**Issue by abeeruzzaman1994** [django-notifications/django-notifications#296]
Is it possile to concatenate notifications?
eg: if in a day 50 users started following me then I wouldn't want 50 notifications. I would like to have a single notification stating "xyz and 49 others started following you"

same goes for comments and likes on a single post

**Comment by darahsten** [comment]
Why not ?, There is absolutely nothing that stops you creating a notification while deactivating other notifications when a threshold is reached. This is not an issue and it will be closed, I would have closed it if I was in charge.

**Comment by abeeruzzaman1994** [comment]
Well @darahsten can you please care to elaborate how I can achieve this feat?

**Comment by darahsten** [comment]
@abeeruzzaman1994, you need to understand for most open source projects people volunteer, you must do your part in reading the documentation and where it is not enough, you can always refer to the source code. In fact you should always read the source code to see how things are done. That even gives you more super powers to learn how to program. None of the volunteers here are going to spend their time teaching you how to code or how to read code or spend time solving your very personal challenges.

That said;
You can do pseudo code it in this way; Assuming you know how to send a notification.
`On event requiring notification
  do we any unread notifications of the same time for the same person:
           are the notifications count equal to a specific number
                 get those notifications
                 mark those notifications as read or soft delete or delete them if you so wish
                 send out a new notification with information suggestion x number of new notifications
 issue new notification to user.`

**Comment by LegoStormtroopr** [comment]
As @darahsten has said, this is definitely possible - but will require some pretty substantial development.

Happy for you to contrib you to the source @abeeruzzaman1994 .

Closing as this isn't an issue.

**Comment by abeeruzzaman1994** [comment]
Thank you so much @darahsten
