### ISSUE TITLE
Maybe documentation problem

### ISSUE THREAD

**Issue by pinkynrg** [django-notifications/django-notifications#299]
There is an example where the model gets overridden.

```
class Notification(AbstractNotification):
...
```

In order for it to work in the custom Notification model's Meta app_label must be added like so:

```
app_label = 'custom_notifications'
``` 

Maybe it should be added in the documentation.

**Comment by AlvaroLQueiroz** [comment]
I'm not sure if I understand what you try to say, but on the [Django docs](https://docs.djangoproject.com/en/4.2/topics/db/models/#be-careful-with-related-name-and-related-query-name), the parameter `app_label` is not mandatory. What is needed to do is add `related_name="%(app_label)s_%(class)s_related"`and `related_query_name="%(app_label)s_%(class)ss"` to **FK** and **MANY2MANY** on base class, what I will do in version 2.

**Comment by tonycchung** [comment]
I have to do this to prevent my custom model from clashing with the reverse lookup related_name from the base Notification model:

```
notifications.Notification.action_object_content_type: (fields.E304) Reverse accessor 'ContentType.notify_action_object' for 'notifications.Notification.action_object_content_type' clashes with reverse accessor for 'my_notification.MyNotification.action_object_content_type'
```
