### ISSUE TITLE
Removing notification after creating then?

### ISSUE THREAD

**Issue by ashmlk** [django-notifications/django-notifications#300]
Hello, I am trying to remove a notification after creating it in my views but I cannot find a way to do so. How can I remove notification after creating it

**Comment by darahsten** [comment]
What do you mean to remove notifications after creating it? Notifications are handled via signals. Disconnect the handler from the notify signal or remove the handler function and the notification will go away. FYI, IMHO, this is not an issue. It does not meet the requirements or the quality to satisfy the requirements as an issue. I think StackOverflow would be a better place to ask such a question. But even in that case, you want to provide more context.

**Comment by ashmlk** [comment]
Unfortunately, I was not able to get an answer on SO, so I didn't where to ask. Currently in order to provide more context:

Notifications are created via a send signal:
 `notify.send(sender=user, recipient=other_user, verb=message, target=object`

Now if I want to disconnect the same notification as you mentioned:

`notify.disconnect(sender, receiver, dispatch_uid)` I cannot manage to do so? How can I disconnect the same notification in a separate method? I could not find the correct way to do so.

I am sorry if this is the wrong place, but I would genuinely appreciate any help in this context.

**Comment by JohnnyFang** [comment]
@ashmlk , I'm not sure if I understand what you are trying to do, if you are trying to mark a notification as deleted, why not simply using the ORM? it would look something like this:    
`Notification.objects.filter(id__in=notificacion_ids).update(deleted=True)`   
where notificacion_ids is a list containing the ids of the notification you want to 'delete'

**Comment by JohnnyFang** [comment]
@AhmedYasin487 you would then filter the notifications model using the 'actor' and the 'recipient'. Something like this:
`notification_ids = Notification.objects.filter(actor_object_id=actor.id, recipient_id=user.id).values_list('id', flat=True)`

**Comment by AhmedYasin487** [comment]
@JohnnyFang  Thank you so much. It was help you :)
