### ISSUE TITLE
Naming is too broad

### ISSUE THREAD

**Issue by tarsil** [django-notifications/django-notifications#302]
The name "notifications" is too broad and it clashes with a lot of applications with the same name. Is it possible to make it more unique? Simply adding a unique identifier to the name would suffice.

**Comment by hirokiky** [comment]
I need to create own django application to handle project's notifications, to...

* inherit django-notifications' model
* implement mail sender
* create REST API for notifications

But we need avoid the name `notifications` in our project. so these will be like `proj_notifications` or `mynotify` or so.
I know this change is really really difficult for django-notifications, but `djnotifications` or `djnotify` is helpful.

**Comment by LegoStormtroopr** [comment]
Unfortunately this would require renaming the entire library, and updating everything in this library.

If it clashes with your project, is it possible to rename your new project?

I'm going to close this issue, but if someone can open a PR to rename this with a clear deprecation cycle, that would be ok.
