### ISSUE TITLE
What is the intention of writing this?

### ISSUE THREAD

**Issue by ibrag8998** [django-notifications/django-notifications#303]
https://github.com/django-notifications/django-notifications/blob/e8d2a251c227ea0e48cf77fd52a91a6cb6882778/notifications/utils.py#L15

**Comment by nemesisdesign** [comment]
That's a good question..

**Comment by AlvaroLQueiroz** [comment]
I believe this was made to not "expose" the object id, but doesn't make sense. I will remove this on version 2.
