### ISSUE TITLE
Allow CSP nonce to be automatically included in `{% register_notify callbacks %}` template

### ISSUE THREAD

**Issue by andrew-m-h** [django-notifications/django-notifications#304]
Hi Devs,

I'm implementing a [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which requires all inline style tags to have a 'nonce' value. In django this is generated by [django-csp](https://django-csp.readthedocs.io/en/latest/).

However, when using register_notify_callbacks in my templates, there  is no way to add a [nonce](https://stackoverflow.com/questions/42922784/what-s-the-purpose-of-the-html-nonce-attribute-for-script-and-style-elements) attribute to the inline script that is generated.

I propose that a simple argument is provided which allows the caller to specify the nonce like so:
```
{% register_notify_callbacks nonce="{{ request.csp_nonce }}" %}
```

**Comment by kunambi** [comment]
I suggest that you override the template that they're using. Check this link on how you override templates: https://docs.djangoproject.com/en/3.1/howto/overriding-templates/

Good luck!
