### ISSUE TITLE
Is there a way to modify the ORM query?

### ISSUE THREAD

**Issue by kunambi** [django-notifications/django-notifications#305]
In the class `NotificationQuerySet` there are a good number of well defined filters. 

Our project would need us to allow to set our own `.order_by()` to e.g. `self.filter(unread=True, deleted=False).order_by('level')`.

Is it possible to override one or more methods?

TYIA

**Comment by AlvaroLQueiroz** [comment]
You can create your own models inheriting from `notifications.base.models.AbstractNotification` and `notifications.base.models.NotificationQuerySet` and add what you need.
