### ISSUE TITLE
This package is not entirely suitable for django rest framwork

### ISSUE THREAD

**Issue by theN0b0dy** [django-notifications/django-notifications#307]
I want to use this package for Django Rest Framework and for some cases I need to make more changes. If you wish, I can fork this repository and write it more specifically for Django Rest Framework.

**Comment by thejpanganiban** [comment]
How so?

You can customize the Notification model by inheriting from `AbstractNotification` and setting it as the Notifcation Model in `settings.py`.

You can then create a new Serializer for your own use case.

**Comment by Nadjedu** [comment]
This package looks abandoned. Are there alternatives?

**Comment by iamAmirrezaSaki** [comment]
you can also use my package [](https://github.com/iamAmirrezaSaki/django-rest-notifications) that its a fork from this package and also it's better for django rest framework

**Comment by bsolomon1124** [comment]
@theN0b0dy it looks like this issue was opened just so that you could advertise your own fork.

It would be more helpful if you can state in your original post the reasons that django-notifications "is not entirely suitable" for DRF. How specifically is it not suitable and what does your fork address?

**Comment by theN0b0dy** [comment]
it's not so different from the original version(README.md is not up to date), the changes that I and https://github.com/The-Daishogun has made are:
- updating `views.py` for using DRF views and also adding `JWT` authentication
- adding pagination to the views and also adding `serializers.py`
- we also removed the sections that were used to switch between versions 2 and 3 of Django ( I think supporting version 2 not necessary )
- I may have forgotten some of the changes

**Comment by AlvaroLQueiroz** [comment]
This project intends to work with pure Django and with the minimum number of dependencies. So, we are not interested in changing to use the DRF. But you can do this by just writing the serializers and views based on the DRF approach.
