### ISSUE TITLE
Use of non-default value for DEFAULT_AUTO_FIELD will trigger migration warning

### ISSUE THREAD

**Issue by rpkilby** [django-notifications/django-notifications#314]
Django 3.2 introduced [`DEFAULT_AUTO_FIELD`](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys) to allow for the customization of auto-created PK fields. Since auto-created PKs are historically `AutoFields`, changing this to anything else (e.g., `BigAutoField`) will trigger a migration warning in django-notifications (and any other third party app with models for that matter). 

I believe that the correct way for django-notifications to fix this is to set the preferred `default_auto_field` in the app config and generate the corresponding migration if necessary.

**Comment by bsolomon1124** [comment]
Addressed by https://github.com/django-notifications/django-notifications/pull/327 though that PR does not include a migration file. (Uncertain if needed.)

**Comment by pandafy** [comment]
I think this can be closed now. 😄
