### ISSUE TITLE
Currently incompatible with Django 4.0: uses providing_args argument

### ISSUE THREAD

**Issue by Flimm** [django-notifications/django-notifications#322]
I've installed the newly released Django 4.0. I get an error when running this code:

```
from notifications.signals import notify
```

The error is: 

```
  File "example/.venv/lib/python3.9/site-packages/notifications/signals.py", line 5, in <module>
    notify = Signal(providing_args=[  # pylint: disable=invalid-name
TypeError: __init__() got an unexpected keyword argument 'providing_args'
```

As you can see [in the release notes for Django 4.0](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0), this version no longer supports the `providing_args` named argument for `Signal`.

**Comment by Flimm** [comment]
The fix is as easy as modifying `notifications/signals.py` to change this line from:

```
notify = Signal(providing_args=[  # pylint: disable=invalid-name
    'recipient', 'actor', 'verb', 'action_object', 'target', 'description',
    'timestamp', 'level'
])
```

to:

```
notify = Signal()
```

**Comment by alor** [comment]
can we expect a new release soon or is the project considered abandoned?  latest release 2 years ago...

**Comment by dmytrotrunykov** [comment]
Wait for the fix too.

**Comment by max-wittig** [comment]
@PetrDlouhy Would you consider reviewing an MR to fix this, if we created one?

**Comment by PetrDlouhy** [comment]
@max-wittig I can review, but I have no rights to merge. @nemesisdesign Did merge my MR a year ago.

**Comment by omkarhunaji** [comment]
File "D:\FSWD\Django\workspacenew\Lib\site-packages\corsheaders\middleware.py", line 14, in <module>
    from corsheaders import signals
  File "D:\FSWD\Django\workspacenew\Lib\site-packages\corsheaders\signals.py", line 5, in <module>
    check_request_enabled = django.dispatch.Signal(
        providing_args=["request"]
    )
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'
