### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by bsolomon1124** [django-notifications/django-notifications#325]
Hello @AlvaroLQueiroz, @nemesisdesign, @LegoStormtroopr, @yangyubo, @zhang-z.

Is this project actively maintained, or is there any intent to support Django 3.1+ and Django 4.0?

I fully realize this is a free open-source project and no one is under an obligation to maintain the project.

If there is no expectation that issues or pull requests will be addressed, perhaps a disclaimer could be made at the top of the README.rst stating that support has been frozen for the time being.

**Comment by yangyubo** [comment]
We are looking for contributors, for anyone who'd like to contribute and willing to put time and energy on this project, please contact me so that I can add you to the maintainer list.

**Comment by bsolomon1124** [comment]
@yangyubo you may have better luck finding contributors and maintainers if you could help those potentially interested to understand:

- Are any of the currently-listed [core contributors](https://github.com/django-notifications/django-notifications#django-notifications-team) active with the project in any way? Do any of them have the ability to at least participate in triaging PRs and Issues?
- If not, is the current core contributors list willing to hand over the keys to the kingdom with a PyPI upload password when new releases are published?

It can be somewhat intimidating for people unfamiliar with the development background of the project to come in and become the sole and core maintainer without a more identifiable succession and handover plan. Especially for a project like this, which is used by many already and has the potential for that to continue if it can keep pace with Django+Python.

**Comment by bsolomon1124** [comment]
(One way to help with this would be the addition of a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file.)

**Comment by pclumson1** [comment]
@bsolomon1124 , I completly agree with you. As I have to tried to make a contribution without anyone response.

It will be nice if this could be actively maintained. I would like to be a volunteer to help update the source code to be compatible with Django 4.0

**Comment by pclumson1** [comment]
@yangyubo  could you please advise on how anyone can effectively contribute to this source code ?

**Comment by derek-adair** [comment]
I can probably spearhead the migration of this to jazzband (i am a member).  If no one has access to the pypi creds I am willing to create/publish a fork as well.  I have experience doing this with other projects, the largest/latest being [a fork](https://github.com/derek-adair/nflgame) of [nflgame](https://github.com/BurntSushi/nflgame).

This is an essential piece of two distinct projects i'm working on so once I have learned this code base I will likely take a stab at doing this.

**Comment by pclumson1** [comment]
I will be helping on this project actively also. I will check what the
issue are and eventual work on the ones that I can do.

**Comment by derek-adair** [comment]
I would love to triage for you; I derive much pleasure from closing issues and telling people to take their "How do i code python?" questions elsewhere.... respectfully.  Here is my general rules for my public issue trackers which help keep the tracker clean and focused.  Maybe they are common sense, maybe not... regardless;

1. **Immediately close (most) support requests.** - create a discord, point them there to ask for help if its relevant to THIS code base.  I **personally** do not help people learn via these channels and direct them to relevant resources to learn or ask questions.  
3. **Close stale issues** - a lot of people just dont follow through with bugs, features, etc etc.
4. **Re Open Issues** - when someone comes back "online" or another user picks up the torch.


Also, one of the first things I would do is create an issue template.  There are many examples to be copied / modified.  Feel free to ping me directly via my website (listed in profile).

**Comment by AlvaroLQueiroz** [comment]
> I would love to triage for you; I derive much pleasure from closing issues and telling people to take their "How do i code python?" questions elsewhere.... respectfully. Here is my general rules for my public issue trackers which help keep the tracker clean and focused. Maybe they are common sense, maybe not... regardless;
> 
> 1. **Immediately close (most) support requests.** - create a discord, point them there to ask for help if its relevant to THIS code base.  I **personally** do not help people learn via these channels and direct them to relevant resources to learn or ask questions.
> 2. **Close stale issues** - a lot of people just dont follow through with bugs, features, etc etc.
> 3. **Re Open Issues** - when someone comes back "online" or another user picks up the torch.
> 
> Also, one of the first things I would do is create an issue template. There are many examples to be copied / modified. Feel free to ping me directly via my website (listed in profile).

Thanks for the support man. And I really liked the idea of the issue template. Fell free to start.

**Comment by derek-adair** [comment]
Here ya go,  from [repo of issue templates](https://github.com/stevemao/github-issue-templates) -- [converstaional](https://github.com/stevemao/github-issue-templates/blob/master/conversational/ISSUE_TEMPLATE.md).

```
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.


* **Do you want to request a *feature* or report a *bug*?**



* **What is the current behavior?**



* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).



* **What is the expected behavior?**



* **What is the motivation / use case for changing the behavior?**



* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]


* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

```
