### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by pandafy** [django-notifications/django-notifications#326]
Is it a good time to issue a release? 

Since support for Dajngo 4.0 has been recently added, I think it will be great to have that available on PyPI.

**Comment by gorkemarslan** [comment]
Any progress?

**Comment by max-wittig** [comment]
To use it, I've now set it in poetry like so. For some reason, it's very common to not release frequently in the Python ecosystem.

```yaml
django-notifications-hq = { git = "https://github.com/django-notifications/django-notifications.git", rev = "0fd3f42f71c19ae75348425686a2fe68ffe04fec" }
```

**Comment by gorkemarslan** [comment]
Dear @max-wittig, thank you for your response.
We use `pip` and `requirements.txt` together to manage dependencies but after your post, I've just checked that it is also possible to specify git repositories into `requirements.txt` file. 

For those who use `pip` and r`equirements.txt`, please remove the line related to `django-notifications-hq` and add this instead:

```
git+https://github.com/django-notifications/django-notifications.git@0fd3f42f71c19ae75348425686a2fe68ffe04fec
```

**Comment by max-wittig** [comment]
Nice! Why don't you release that often though. Is there a reason? @gorkemarslan

**Comment by gorkemarslan** [comment]
@max-wittig, I want to clarify that I am not a maintainer of this project. 😄 

In our project, which is another one so not `django-notifications`, we try to update it to Django 4. The only package that is not compatible with Django 4 is `django-notifications`.
