### ISSUE TITLE
Installation problem in Django 4.0

### ISSUE THREAD

**Issue by mofizul21** [django-notifications/django-notifications#330]
Hi, I'm trying to use this package with my Django 4.0. But I see an error when I put `INSTALLED_APPS = [ 'notifications',]` And when I comment out the line, the error has gone.

Here I've pasted the error message- https://pastebin.com/DR44BAWY

How I can fix it?

**Comment by AlvaroLQueiroz** [comment]
Will be fully fixed on version 2
