### ISSUE TITLE
The costumed notification template does not work

### ISSUE THREAD

**Issue by akenore** [django-notifications/django-notifications#339]
hi i try to make custom template for notification but it dosn't work

i have add this code to my template

                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">

                      <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>

                      {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
                        
                        <div class="card" style="width: 290px">
                            <div class="card-header">All notification</div>
                            <div class="card-body">
                                {% live_notify_list %}
                          

                            </div>
                            <div class="card-footer text-muted">
                                
                                <a href="{% url 'notifications:mark_all_as_read' %}?next={{request.path}}" class="btn btn-link float-end">{% translate "Clear all" %}</a>
                                
                            </div>
                        </div>
                        
                        
                       
                    </ul>
and what i got is what is in this pic can you please help me and thanks

<img width="269" alt="Screen Shot 2022-06-16 at 10 16 16 PM" src="https://user-images.githubusercontent.com/57950197/174169696-582e9097-41b3-400c-91ee-9a8281769f76.png">

**Comment by soysushi** [comment]
did you load the notification tags? {% load notifications_tags %}
