### ISSUE TITLE
How can I add Notifications Model into my Admin？

### ISSUE THREAD

**Issue by bigrich-luo** [django-notifications/django-notifications#340]
Hi there,

I wanna add Notifications Model into my own project, and then I did below actions

`admin.py

from notifications.admin import NotificationAdmin, Notification

admin.site.register(Notification, NotificationAdmin)`

However, this didn't work and return error.

**Comment by soysushi** [comment]
Your error probably says that it has been registered already. 

There's no need for you to register it again to your project since notifications has an admin.py

**Comment by bandarAlrooqi** [comment]
it should be already there, you don't need to write the above code + Notification in models not in admin. 
if it does not appear make sure you included 'notifications' as the last one in your INSTALLED_APPS.
