### ISSUE TITLE
Custom JavaScript callback not working 

### ISSUE THREAD

**Issue by Znydee** [django-notifications/django-notifications#342]
Hi, i have been trying to use a custom JavaScript callback as shown in the documentation but it ain't working. Please, ion know if it is a bug or i ain't doing it correctly .Thanks

**Comment by Znydee** [comment]
Thanks a lot guys, i figured it out. I think i should post what i did just in case someone stuck with this same problem comes across this.

-clone the repo and install it from source as in the documentation
- in the "django-notifications/notifications/static/notifications" of the cloned repository, copy the file "notify.js" and paste it in your apps static folder.
-open the "notify.js" file in your apps static folder and add your custom callback function...thats all.
(make sure to add your function name to the callback list in the register_notify_callback tag in your html template as shown in the documentation)

**Comment by AlvaroLQueiroz** [comment]
I'm not sure how you were doing this, but it's not necessary to override the `notify.js`
