### ISSUE TITLE
Deprecation Warning related to distutils package

### ISSUE THREAD

**Issue by DamyanBG** [django-notifications/django-notifications#344]
The package distutils will be deprecated. There are few deprecation warnings. I suggest to use packaging instead distutils or show me some way to fix my warnings. https://github.com/django-notifications/django-notifications/blob/e8d2a251c227ea0e48cf77fd52a91a6cb6882778/notifications/urls.py#L1-L3

**Comment by brylie** [comment]
We are also getting the following deprecation warnings.

> notifications/base/models.py:22: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.8.0'):
>
> notifications/views.py:20: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
>
> notifications/urls.py:9: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

**Comment by KanishkaHalder1771** [comment]
Hi, I was trying to fix a downstream issue [https://github.com/CiviWiki/OpenCiviWiki/issues/1426](https://github.com/CiviWiki/OpenCiviWiki/issues/1426)
Created a PR for fixing this issue
@AlvaroLQueiroz please review it once: https://github.com/django-notifications/django-notifications/pull/370

**Comment by AlvaroLQueiroz** [comment]
Fixed by #372 will be released in the next version.
