### ISSUE TITLE
Field 'id' expected a number but got '<property object at 0x7fe908ebc900>'.

### ISSUE THREAD

**Issue by soysushi** [django-notifications/django-notifications#345]
Not sure why this is happening when you view the model inside django-admin 

end point is 

http://localhost:8000/admin/notifications/notification/

**Comment by soysushi** [comment]
The solution was found by my colleague. There is something wrong when you use the default Notification model, the bug disappears if I simply use my own model while extending AbstractNotification model.

`class Notification(AbstractNotification):
    # custom field example
    

    class Meta(AbstractNotification.Meta):
        abstract = False
`

**Comment by amitv9493** [comment]
Hi I m facing the same issue. Also I am new to django could you please explain more about how you get rid of this error?

**Comment by AlvaroLQueiroz** [comment]
Can you give more information about how to produce this error?

**Comment by AlvaroLQueiroz** [comment]
Nice, thanks for the detailed response. I will take a look carefully at this on V2.
