### ISSUE TITLE
Filter out 200 messages

### ISSUE THREAD

**Issue by Samoht1** [django-notifications/django-notifications#346]
Is there a way to filter out all the `INFO "GET /inbox/notifications/api/unread_list/?max=5 HTTP/1.1" 200 2543` messages when running the server?

**Comment by AlvaroLQueiroz** [comment]
You can write a logger handler with a special filter for this endpoint. 

[Handlers doc](https://docs.djangoproject.com/en/4.2/topics/logging/#topic-logging-parts-handlers)
[Filter doc](https://docs.djangoproject.com/en/4.2/topics/logging/#topic-logging-parts-filters)

**Comment by Samoht1** [comment]
I am aware of that, but I don’t want to filter out ALL info messages but just those produced from this package specifically.

On 27 May 2023, at 4:26 PM, Alvaro Leonel ***@***.***> wrote:

﻿

You can write a logger handler with a special filter for this endpoint.

Handlers doc<https://docs.djangoproject.com/en/4.2/topics/logging/#topic-logging-parts-handlers>
Filter doc<https://docs.djangoproject.com/en/4.2/topics/logging/#topic-logging-parts-filters>
