### ISSUE TITLE
Python 3.4.1 not supported

### ISSUE THREAD

**Issue by H4x0rjax** [django-notifications/django-notifications#35]
for example, usage of the "unicode()" constructor is not supported in up-to-date python versions..

**Comment by LegoStormtroopr** [comment]
Has this been merged in and made a release? I'd like to be able to use a pip release in a test suite.

**Comment by naderm** [comment]
I don't think so. I ended up dropping support for py3 in my application due to conflicts with other dependencies, but you're welcome to fork my change, merge the most recent master, and make a pull request for this issue.

**Comment by naderm** [comment]
Oh, there were some changes for py3 since my fork, 8c7cc0d3c13f2aedaca1642e3bf59f21202fc7da. I added tests to check for unicode support though^^

**Comment by ryangallen** [comment]
Bump. Any idea when this will be addressed @yangyubo?

**Comment by yangyubo** [comment]
@ryangallen Pull requests are welcome

**Comment by LegoStormtroopr** [comment]
I can take a look at this over the weekend. Nadern seems to have done quite a bit of good work, so I'll see how easy it is to catch up from there.

**Comment by yangyubo** [comment]
This issue was fixed, as state by @LegoStormtroopr in #47. If someone still come across the issue, please reopen it.
