### ISSUE TITLE
ugettext_lazy has been removed in Django 4.0 

### ISSUE THREAD

**Issue by AtitBimali** [django-notifications/django-notifications#357]
**Django 4.0 Release Note:**
django.utils.translation.ugettext(), ugettext_lazy(), ugettext_noop(), ungettext(), and ungettext_lazy() will be removed.

Source: [Django's Official](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-4-0)

Error:

> File "site-packages/notifications/models.py", line 3, in <module>
>     from .base.models import AbstractNotification, notify_handler  # noqa
>   File "site-packages/notifications/base/models.py", line 14, in <module>
>     from jsonfield.fields import JSONField
>   File "site-packages/jsonfield/__init__.py", line 1, in <module>
>     from .fields import JSONCharField, JSONField  # noqa
>   File "/site-packages/jsonfield/fields.py", line 8, in <module>
>     from django.utils.translation import ugettext_lazy as _
> ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/atit/.local/lib/python3.10/site-packages/django/utils/translation/__init__.py)

**Temporary Solution**
Use Django version < 4.0

**Comment by stefflc** [comment]
We are also running into this issue. Project is marked as working for Django 4.0 and 4.1, but it is not compatible.

**Comment by AlvaroLQueiroz** [comment]
Fixed on [Version 2](/django-notifications/django-notifications/tree/v2-alpha)
