### ISSUE TITLE
Release 1.8.0 migrations

### ISSUE THREAD

**Issue by mfisco** [django-notifications/django-notifications#363]
Release 1.8.0 introduced some model changes which necessitated a migration; however, the release didn't contain a new migration. Do you know if this was intentional? If not, I'd happily submit a PR with the migration. 

Thank you for maintaining the project!

**Comment by christianwgd** [comment]
Seems like 1.8.1 should fix this but the pypi release for 1.8.1 still doesn't include the migration file (0009...).
