### ISSUE TITLE
add uuid to indentify notifications

### ISSUE THREAD

**Issue by brahim024** [django-notifications/django-notifications#367]
What if we consider adding UUIDs to identify notifications, making it easier to edit notifications using the API

**Comment by koleror** [comment]
Indeed, that'd be awesome! 
Any chance to make this happen?

**Comment by mrakhror** [comment]
from notifications.base.models import AbstractNotification
from uuid import uuid4
class Notification(AbstractNotification):
    uuid = models.UUIDField(
        primary_key=True, unique=True, default=uuid4, editable=False
    )

    class Meta(AbstractNotification.Meta):
        abstract = False
