### ISSUE TITLE
Missing static files in PyPI package of 1.8+ 

### ISSUE THREAD

**Issue by danialkeimasi** [django-notifications/django-notifications#368]
Hello, I hope you're doing well.

It seems that the `notification/static` directory is missing in PyPI after the `1.8.0` builds.

I have built the master branch of this repository, and the resulting build includes the notification/static directory.

Also, I have noticed that this repo is outdated compared to the code available in the PyPI build. The latest version in the repository is `1.8.0`, whereas PyPI has `1.8.2`. I have compared the build with this repository, I found that only the 0009 migration (#365) has not been pushed to the repository.

**Comment by danialkeimasi** [comment]
Is maintenance still ongoing for this project? @yangyubo

**Comment by danialkeimasi** [comment]
Is this project still maintained? @yangyubo

**Comment by rez0n** [comment]
Hi, same issue. Here is structure of the package

```
.
|-- __init__.py
|-- admin.py
|-- apps.py
|-- base
|   |-- __init__.py
|   |-- admin.py
|   `-- models.py
|-- helpers.py
|-- locale
|   `-- ru
|       `-- LC_MESSAGES
|           `-- django.po
|-- migrations
|   |-- 0001_initial.py
|   |-- 0002_auto_20150224_1134.py
|   |-- 0003_notification_data.py
|   |-- 0004_auto_20150826_1508.py
|   |-- 0005_auto_20160504_1520.py
|   |-- 0006_indexes.py
|   |-- 0007_add_timestamp_index.py
|   |-- 0008_index_together_recipient_unread.py
|   |-- 0009_alter_notification_options_and_more.py
|   `-- __init__.py
|-- models.py
|-- settings.py
|-- signals.py
|-- templates
|   `-- notifications
|       |-- list.html
|       |-- notice.html
|       `-- test_tags.html
|-- templatetags
|   |-- __init__.py
|   `-- notifications_tags.py
|-- tests
|   |-- __init__.py
|   |-- sample_notifications
|   |   |-- __init__.py
|   |   |-- admin.py
|   |   |-- apps.py
|   |   |-- migrations
|   |   |   |-- 0001_initial.py
|   |   |   `-- __init__.py
|   |   |-- models.py
|   |   |-- templatetags
|   |   |   |-- __init__.py
|   |   |   `-- notifications_tags.py
|   |   `-- tests.py
|   |-- settings.py
|   |-- templates
|   |   `-- test_live.html
|   |-- tests.py
|   |-- urls.py
|   `-- views.py
|-- urls.py
|-- utils.py
`-- views.py
```

CC @AlvaroLQueiroz

**Comment by TannicArturo98** [comment]
You could create **notifications** folder inside the **static** folder.

![image](https://github.com/django-notifications/django-notifications/assets/53819131/ccda9901-1273-44f5-b7dd-7730a79c4c86)

Check if your Django project get static files from static folder.

**Comment by AlvaroLQueiroz** [comment]
Sorry for the delay guys. I fixed the static [issue](https://github.com/django-notifications/django-notifications/commit/f46e46887a8be4f52875c7a2816e3687fbba9b82) on [V1.8.3](https://pypi.org/project/django-notifications-hq/1.8.3/) and updated the [build](https://github.com/django-notifications/django-notifications/releases/tag/1.8.3) and [tags](https://github.com/django-notifications/django-notifications/tags) here on GH.
