### ISSUE TITLE
NoReverseMatch django.urls.exceptions.NoReverseMatch: Reverse for 'mark_as_read' with no arguments not found. 1 pattern(s) tried: ['inbox/mark-as-read/(?P<slug>\\d+)/$']

### ISSUE THREAD

**Issue by reyesvicente** [django-notifications/django-notifications#373]
**Describe the bug**

**To Reproduce**
1. Install django-notifications-hq
2. Place `<a href="{% url 'notifications:mark_as_read' %}">Mark as read</a>` in html template

**Expected behavior**
The url should work as expected

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Python version 3.11
 - Lib version 

**Additional context**

**Comment by AlvaroLQueiroz** [comment]
Have you added the Django-notifications URLs to your project URLs?

```python
import notifications.urls

urlpatterns = [
    ...
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    ...
]```

**Comment by AlvaroLQueiroz** [comment]
You need to pass the `slug` as argument, like this:

`<a href="{% url 'notifications:mark_as_read' notification.slug %}">Mark as read</a>`
