### ISSUE TITLE
Difference with Django-Activity-Stream

### ISSUE THREAD

**Issue by rchrd2** [django-notifications/django-notifications#41]
Hello, in your readme, you note this was derived from [Django-Activity-Stream](https://github.com/justquick/django-activity-stream). Besides the name, what distinguishes this package from D.A.S?

If there is something obvious, it could be helpful to add it to the readme to aid developers evaluating the many choices of activity packages.

Thank you.

**Comment by LegoStormtroopr** [comment]
+1 'd be curious to know the reason to, but it seems like part of it is because DAS has gone a bit stale.

**Comment by yangyubo** [comment]
Take Github as an example, django-notifications is for building something like Github notifications, while Django-Activity-Stream is for building Github "News Feed"

**Comment by yangyubo** [comment]
The major difference is stated in README.rst
