### ISSUE TITLE
Configure continuous testing

### ISSUE THREAD

**Issue by LegoStormtroopr** [django-notifications/django-notifications#48]
It'd be handy to have a continuous testing suite configured so as pull requests come in we can easily verify the integrity of the code.

I've used travis-CI and Coveralls on a few projects and its really handy. Unfortunately, only project owners or members of the organisation can do this. If you haven't got the time, if you add me in I'd be happy to volunteer to do this as its relatively straight forward. You can then remove me after as its a one time setup.

**Comment by yangyubo** [comment]
@LegoStormtroopr invited, thank you for being part of this project. And if you’re willing, you can always contribute to this project.
