### ISSUE TITLE
PIP out of date.

### ISSUE THREAD

**Issue by LegoStormtroopr** [django-notifications/django-notifications#50]
The PIP page at https://pypi.python.org/pypi/django-notifications-hq/
Still lists the package as living at http://github.com/brantyoung/django-notifications

Also the last official release was in May last year. Is it possible to push some of the latest changes into a new version?

**Comment by yangyubo** [comment]
@LegoStormtroopr I'll push a new release WHEN you think version 0.6.3 is ready.

**Comment by LegoStormtroopr** [comment]
@yangyubo I've created a new pull request ( #51 ) for extra coverage and confirms Django 1.8 support. If you are happy to pull those changes in, I'd vote for a 0.6.3 release.

Thoughts?

**Comment by yangyubo** [comment]
@LegoStormtroopr Nice work! I'd like to find an afternoon to convert current packaging format from egg to wheel, then push the new release.

**Comment by LegoStormtroopr** [comment]
No worries, I'm glad to help. This is a really nifty library.
