### ISSUE TITLE
Serializing the django-notifications Model

### ISSUE THREAD

**Issue by DaWy** [django-notifications/django-notifications#53]
I'm trying to **serialize the model** included in django-notifications package with DRF (for a RESTFUL API)

But i'm facing a problem. When I acces the model Notification inside notifications\models.py and try to make a ModelSerializer of it, then raise this error:

`NotificationQuerySet' object has no attribute 'recipient'.`

My ModelSerializer:

```
class NotificationSerializer(serializers.ModelSerializer):

    class Meta:
        model = Notification
        fields = ('description', 'recipient',)
```

Any tip on this? I don't understand why is trying to accesing NotificationQuerySet instead of Notification model...

Thanks in andvance.

**Comment by mwcbrent** [comment]
I know this is a really old question but I solved this recently and wanted to share my solution.  My solution took advantage of the generic foreign key support in django rest framework.  See below:

```
class GenericNotificationRelatedField(serializers.RelatedField):

    def to_representation(self, value):
        if isinstance(value, Foo):
            serializer = FooSerializer(value)
        if isinstance(value, Bar):
            serializer = BarSerializer(value)

        return serializer.data


class NotificationSerializer(serializers.Serializer):
    recipient = PublicUserSerializer(User, read_only=True)
    unread = serializers.BooleanField(read_only=True)
    target = GenericNotificationRelatedField(read_only=True)
```

See here - http://www.django-rest-framework.org/api-guide/relations/#generic-relationships

**Comment by soncojmk** [comment]
I just had this problem and you solved it for me. So thank you for taking the time to answer the question even if it was two years old

**Comment by AlvaroLQueiroz** [comment]
Added the exemple in README file. Thanks @DaWy .

**Comment by mayankwadhwani** [comment]
@mwcbrent Any Idea on how to update the read status ?

**Comment by mwcbrent** [comment]
This is a while back so the context is gone but my sense is that you could remove the `read_only` argument and perhaps handle that value being passed is a view.  I'd refer to this line https://github.com/django-notifications/django-notifications/blob/master/notifications/views.py#L78
