### ISSUE TITLE
NOT NULL constraint failed: notifications_notification.deleted

### ISSUE THREAD

**Issue by niknokseyer** [django-notifications/django-notifications#59]
I'm getting the error: NOT NULL constraint failed: notifications_notification.deleted when I try to add a new notification.

**Comment by zhang-z** [comment]
Can you paste the codes that trigger this error? And which version are you using, 0.7.0 / master / else?

**Comment by niknokseyer** [comment]
I did a:
`pip install django-notifications-hq --upgrade`

I've been encountering this issue for a while now as I've been transferring from workstations.
But suddenly after trying it again right now I'm not getting the error anymore. Will try to reproduce it and get some more information.
