### ISSUE TITLE
Deprecation warning: RemovedInDjango19Warning

### ISSUE THREAD

**Issue by stripathi669** [django-notifications/django-notifications#62]
I can see following warning in Django 1.8:

django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.

    from django.contrib.contenttypes import generic

**Comment by zhang-z** [comment]
Hi, this issue has been fixed in pull request #57. You can install from latest master branch to solve it: `pip install git+https://github.com/django-notifications/django-notifications.git`
