### ISSUE TITLE
Any tutorial out there?

### ISSUE THREAD

**Issue by qasimalbaqali** [django-notifications/django-notifications#66]
It's a bit confusing for a newbie to use it. Is there a real app tutorial out there for django-notifications?

**Comment by zhang-z** [comment]
Hi qasimalbaqali, as I know, the README.rst on project home page is the only guide, at this moment.

**Comment by qasimalbaqali** [comment]
That's a shame, thank you for the reply.

**Comment by gitiup** [comment]
A tutorial on how to integrate this with admin would be very helpful.

**Comment by yangyubo** [comment]
@gitiup We don't have a tut for admin integration, but we provide a [admin.py](https://github.com/django-notifications/django-notifications/blob/master/notifications/admin.py), so the integration is very straightforward.

Please feel free to add docs for admin integration or improve the `admin.py` module. You can find more info about django admin from https://docs.djangoproject.com/en/1.9/ref/contrib/admin/

**Comment by gitiup** [comment]
Thank you Yang.

I will start on it, your notification module seems very interesting but it looks like there are a lot of people having a hard time to integrate it with the admin.

I will try to document it and see how it goes. If I get it working with the admin interface I like to add the documentation to your github so others can use it.

Will you provide some help if needed?

Thanks.

**Comment by yangyubo** [comment]
I will for sure. Please file a pull request once you've finished.

Thank you

**Comment by gitiup** [comment]
I will do Yang.

I must admit I am starter in django but I have done a full site in admin and it works great. Been working on it day and night for a month.
So I may have some basic questions that you think it very basic but I pick up quickly.

So I will start on it tonight.
:)
Once I am done. I like to document it step by step so there are no questions.

Thanks.

**Comment by mezitax** [comment]
So, there is still no django-notifications tutorial?
