### ISSUE TITLE
Emailing Notification

### ISSUE THREAD

**Issue by sheepeatingtaz** [django-notifications/django-notifications#67]
Hi All,

I might be being dense - if so apologies!

I can see a model field for 'emailed', but cannot see a way to actually trigger sending an email to the recipient. How does one do this?

Thanks

**Comment by zhang-z** [comment]
Hi sheepeatingtaz, the feature of sending email is not integrated in django-notifications, because emails could be quite project-specific. Projects that require this feature need to implement it by themselves. The reserved "emailed" field can make it a little easier to do.

**Comment by satyanash** [comment]
> Projects that require this feature need to implement it by themselves. 

I believe this should be mentioned in the documentation. Even if it's just a single line.

**Comment by zhang-z** [comment]
@satyanash , thanks  just added the [note](https://github.com/django-notifications/django-notifications#email-notification)
