### ISSUE TITLE
Why is pagination ignored in the all() view?

### ISSUE THREAD

**Issue by awidgery** [django-notifications/django-notifications#69]
I'm trying to get pagination working and saw the `page = request.GET.get('p')` code in the `all` view, but it wasn't working.

After a closer look it seems there is a return straight back on lines 19-21:

```
return render(request, 'notifications/list.html', {
    'notifications': qs
})
```

So the code after this never executes.
Is there a reason for this?

**Comment by onyekaa** [comment]
Yeah noticed too today. Had to comment out that line.
