### ISSUE TITLE
?next={{ some_url }} doesn't url_decode {{ some_url }}

### ISSUE THREAD

**Issue by awidgery** [django-notifications/django-notifications#70]
Suppose I send a user to `/inbox/notifications/mark-as-read/111270/` but I want to send them on to another page straight away.

So I use e.g.:

`/inbox/notifications/mark-as-read/111270/?next=/some_page/

But if I want to send them to e.g. `/some_page/?get_var=hello_world` I get stuck. I can urlencode the `?next=` url but django-notifications doesn't decode this correctly.  Is there a reason for this? If not I'll form the repo and add the urldecode to `views.py`'s `_next` bits.

**Comment by AlvaroLQueiroz** [comment]
After some tests, this apparently works perfect.
