### ISSUE TITLE
JSON access to recent notifications

### ISSUE THREAD

**Issue by LegoStormtroopr** [django-notifications/django-notifications#71]
Some projects may find it useful to have an easy to drop in Javascript/JSON function with an appropriate updating field that fetches notifications on behalf of the user:

For example, inserting the code similar to the following into a template:

    {% load notifications_tags %}
    {% live_notify_icon %}

Would provide an auto-updating notification badge indicating there are unread notfications, without a page refresh.

Similarly, something like this:

    {% load notifications_tags %}
    {% live_notify_menu 5 %}

Would provide a simple `ul` menu with the 5 most recent unread notifications (with the number being configurable).

I've assigned this bug to me already and can do some work on it, and if there is interest we can look at pulling it in.

For reference, this would be done in a way that adds no extra requirements, and done using raw javascript so we don't force libraries like jquery onto users.

Any thoughts on this?

**Comment by yangyubo** [comment]
Nice idea!

Just one comment, Is it possible to provide a REST API, allows users fetch unread notification count by what ever js library they preferred? So we do not need a tight coupling between front-end js and back-end functionality.

What do you think?

**Comment by LegoStormtroopr** [comment]
Do you mean, provide an API so the user can make a call to something like `/notifications/api/unread_list/?count=5` to get the most recent unread back? If so, thats definitely a good idea.

At this stage, my plan was to implement a really simple template_tag with plane javascript behind it. Then if people wanted to build from that using jQuery/Prototype/etc, they could.

**Comment by yangyubo** [comment]
Yes, that’s what I mean.

I think your plan is completely fine, since that template_tag out of the box, simple and straightforward, please go ahead on your plan.
