### ISSUE TITLE
Notifications for many users

### ISSUE THREAD

**Issue by danielcb29** [django-notifications/django-notifications#74]
Hi! 

I was checking the project and I found it really great! , I am using it in mi app to notify when a meeting is programed, is edited or is canceled. I need to notify  about the meeting changes for all meeting guests. 

I tried to pass an array in the parameter recipient however it get me an error. Is there any way to notify all my meeting guests about the meeting changes? Can I use the lib for that purpose? 

Thanks! 

Best regards

**Comment by danielcb29** [comment]
I think that using a for loop I can send notifications for many users , but , Is there other way to make it better? 

The solutions that I think is: 

users = User.objects.filter(some_attr=value)
for u in users: 
    notify.send(request.user, recipient=u, verb='some message')

**Comment by yangyubo** [comment]
Currently, `recipient` doesn't accept an array as parameter.

Use a simple loop of course a quick fix, for a better solution, you can fork this project and add `recipients` parameter which accepts an array, and then submit a pull request.

**Comment by Evidlo** [comment]
`recipient` should accept (Groups)[https://docs.djangoproject.com/en/1.9/ref/contrib/auth/#django.contrib.auth.models.Group]

**Comment by yangyubo** [comment]
Fixed in #107 by @Evidlo
