### ISSUE TITLE
Invalid block tag: 'register_notify_callbacks'

### ISSUE THREAD

**Issue by Vido** [django-notifications/django-notifications#75]
Hello guys,

First, i don't know if this is the right channel to place this question. Let me know if there is a more appropriate mail-list.

I'm running Python3.4 and Django1.8. And i'm getting this kind of errors from _register_notify_callbacks_, when rendering the template:

```
TemplateSyntaxError at /dashboard/
Invalid block tag: 'register_notify_callbacks'
{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
```

Are Python3.4 and Django1.8 supported?
Am I missing something? 

```html
<!-- base.html -->
  1 {% load staticfiles %}
  2 {% load notifications_tags %}
 25 
 26     <!-- Django Notifications-->
 27     <script src="{% static 'notifications/notify.js' %}" type="text/javascr
 28     {% register_notify_callbacks callbacks='fill_notification_list,fill_not
 29 
```
```python
# settings.py
 33 INSTALLED_APPS = (
 34     'django_admin_bootstrapped',
 35     'django.contrib.admin',
 36     'django.contrib.auth',
 37     'django.contrib.contenttypes',
 38     'django.contrib.sessions',
 39     'django.contrib.messages',
 40     'django.contrib.staticfiles',
 41     'django_extensions',
 42     'rest_framework',
 43     'water_meter',
 44     'website',
 45     'sabesp',
 46     'bootstrapform',
 47     'localflavor',
 48     'notifications',
 49 )
```

Thanks!

**Comment by Vido** [comment]
Sorry, I have installed from pip. It seems the package is behind the trunk.

**Comment by Narcissist1** [comment]
I got the same problem, how did you solve it ?

**Comment by Vido** [comment]
I just cloned the repo. Than I installed it with `python setup.py install`
I guess they fixed this problem, but they did not uploaded a new package on PyPI.

**Comment by LegoStormtroopr** [comment]
Hi Vido,

Are you still having this issue?

**Comment by yangyubo** [comment]
[Version 0.8.0](https://pypi.python.org/pypi/django-notifications-hq/0.8.0) was uploaded on PyPI
