### ISSUE TITLE
def user_context in notifications_tags does not work

### ISSUE THREAD

**Issue by error0608** [django-notifications/django-notifications#78]
def user_context(context):    
    if 'user' not in context:
        return None

    request = context['request'] <---- don't work in django 1.8.4
    user = request.user
    if user.is_anonymous():
        return None
    return user

**Comment by yangyubo** [comment]
@error0608 Thank you for point out this issue, could you please create a pull request to help fix it?

**Comment by error0608** [comment]
my working version was:
```
def user_context(context):    
    if 'user' not in context:
        return None

    user = context['user']
    if user.is_anonymous():
        return None
    return user
```

**Comment by error0608** [comment]
```
def user_context(context):
  if 'user' not in context:
    return None
  request = context['request'] 
  user = request.user
  if user.is_anonymous():
      return None
  return user
```
This working if add in settings - django.template.context_processors.request. default settings, it is not
