### ISSUE TITLE
get unread notifications list more than 5

### ISSUE THREAD

**Issue by fengdy** [django-notifications/django-notifications#81]
when use  register_notify_callbacks  to get the list of unread notifications objects, the default size is 5, how to get all unread objects use this?  how to send the 'max' value in {% register_notify_callbacks callback='....' %} ?

**Comment by fengdy** [comment]
i find no way to send max value by tag, just set the "max" value in js file

**Comment by LegoStormtroopr** [comment]
I'm reviewing the code for this feature at the moment for #82 and will see what I can figure out.

**Comment by LegoStormtroopr** [comment]
Ok, so the max notifications to fetch is in a get parameter, and the easiest way to set this is to update the `notify_api_url` value *after* you have registered the callback like so:

    {% register_notify_callbacks .... %}
    <script>notify_api_url = 'example.com/notifications/api/<API_TO_CHOOSE>?max=100</script>

Does that fix your question?

**Comment by fengdy** [comment]
maybe the best way to set max is send a parameter in {% register_notify_callbacks ..... %}, and now, i set in in notify.js file

**Comment by LegoStormtroopr** [comment]
I'll definitely consider that as part of the latest lot of bug fixes. If you have a temporary workaround thats great (sorry about the inconvenience).

Can you post an example of your work around to help speed the process?

**Comment by fengdy** [comment]
The default value of max in set in views, In my way, i  modify the templatetags as follows:
def register_notify_callbacks(badge_id='live_notify_badge',menu_id='live_notify_list',refresh_period=15,callbacks="",api_name='list',max=15)  
and send it to the back
if api_name=='list':
        api_url = reverse('notifications:live_unread_notification_list', kwargs={'max':max})

urls.py  modify as follows:
     url(r'^api/unread_list/(?P<max>\d+)/$', 'live_unread_notification_list',     name='live_unread_notification_list'),

views.py:
def live_unread_notification_list(request, max):

maybe it a little chaos, sorry

**Comment by LegoStormtroopr** [comment]
@fengdy I've proposed a fixed PR for this, but would appreciate some peer review if you get a chance.

**Comment by fengdy** [comment]
in the view the function  live_unread_notification_list  not have a  login_required  protect,  maybe cause 'AnonymousUser' object has no attribute 'notifications'  error

**Comment by LegoStormtroopr** [comment]
@fengdy Apologies, I didn't understand this at the time, but do now. I've lodged a new bug for that to be closed there -> #120
