### ISSUE TITLE
New version of django-model-utils doesn't have PassThroughManager

### ISSUE THREAD

**Issue by JamSquad** [django-notifications/django-notifications#87]
New version of django-model-utils doesn't have PassThroughManager.  When I then go pip install --upgrade it errors ```AttributeError: 'module' object has no attribute 'PassThroughManager'```

**Comment by zhang-z** [comment]
Hi @JamSquad , django-model-utils [removed it in version 2.4](https://pypi.python.org/pypi/django-model-utils/). It's supposed to use Django’s built-in QuerySet.as_manager() and/or Manager.from_queryset() utilities instead. But they are [new in Django 1.7](https://docs.djangoproject.com/en/1.8/topics/db/managers/#creating-manager-with-queryset-methods). As django-notifications is still supporting Django 1.4~1.6, a quick fix would be to use lower version of django-model-utils. I created pull request #88 to update the setup.py

**Comment by JamSquad** [comment]
Thanks zhang-z, I've put django-model-utils==2.3.1 in my pip requirements file, and the problem is now fixed.
