### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PassThroughManager'

### ISSUE THREAD

**Issue by chrisspen** [django-notifications/django-notifications#90]
I'm unable to import any notification.models because they reference a manager that no longer exists in a dependent package:

    Traceback:
       File "/usr/local/myproject/src/myproject/myapp/models.py", line 100, in <module>
         from notifications.models import Notification
       File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/notifications/models.py", line 123, in <module>
         class Notification(models.Model):
       File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/notifications/models.py", line 185, in Notification
         objects = managers.PassThroughManager.for_queryset_class(NotificationQuerySet)()
    AttributeError: 'module' object has no attribute 'PassThroughManager'

It looks like [PassThroughManager](https://github.com/carljm/django-model-utils/blob/master/model_utils/managers.py) was removed but the setup.py still allows this incompatible version to be installed.

**Comment by zhang-z** [comment]
@chrisspen , it's discussed in issue #87 . The solution for now is to downgrade django-model-utils to version <2.4. We're also [discussing](https://github.com/django-notifications/django-notifications/issues/89) to stop support for Django 1.4-1.6. If it goes that way, the latest version of django-model-utils will be compatible.
