### ISSUE TITLE
model_utils removed PassThroughManager 

### ISSUE THREAD

**Issue by genxstylez** [django-notifications/django-notifications#92]
prior to model_utils 2.4 the PassThroughManager has been removed.

please see
https://github.com/carljm/django-model-utils/commit/2824ec2e4875ab6530caa440034959d51d5b9830

**Comment by zhang-z** [comment]
Hi @genxstylez , it has been discussed in issue #87  and #90 .  Temp solution is to use model-utils 2.3.1, we're also working on drop support for Django 1.4~1.6 so that model-utils 2.4 will be compatible.
