### ISSUE TITLE
django-model-utils - Remove PassThroughManager

### ISSUE THREAD

**Issue by error0608** [django-notifications/django-notifications#93]
Error in File "\notifications\models.py", line 193, in Notification
    objects = managers.PassThroughManager.for_queryset_class(NotificationQuerySet)()

because

in django-model-utils version 2.4 remove PassThroughManager (https://github.com/carljm/django-model-utils/blob/master/CHANGES.rst)

**Comment by christarazi** [comment]
Refer to issue #92. This has been worked around.
