### ISSUE TITLE
PassThroughManager removed from django-model-utils

### ISSUE THREAD

**Issue by areski** [django-notifications/django-notifications#96]
Recent version of django-model-utils removed PassThroughManager -> https://github.com/carljm/django-model-utils/blob/master/CHANGES.rst

PassThroughManager will need to be replaced here https://github.com/django-notifications/django-notifications/blob/master/notifications/models.py#L193
Use Django's built-in QuerySet.as_manager() and/or Manager.from_queryset() utilities instead.

**Comment by zhang-z** [comment]
Hi @areski  , it has been discussed in issues such as #87 and #90 . Temp solution is to use model-utils 2.3.1. We're also working on drop support for Django 1.4~1.6 so that QuerySet.as_manager() and/or Manager.from_queryset() will be available.

**Comment by areski** [comment]
Thanks for the quick reply, I looked at the open-ticket and didnt find anything. I would advice to not close a ticket if a solution is pending (my 2 cents).

Regarding this issue, model-utils will not work with Django1.9 so we need a fix :)

**Comment by zhang-z** [comment]
Agree, I should have left the ticket open.

The latest code in branch drop-support-django1.6 should work for Django 1.9. Not merged into master yet.

**Comment by areski** [comment]
https://github.com/django-notifications/django-notifications/blob/drop-support-django1.6/notifications/models.py#L193 
ohhhh nice, thanks for that! Any plan to merge/release ?

**Comment by zhang-z** [comment]
Currently waiting for some updates, then bump the last Django1.4-supported version, as discussed in issue #89 . I guess within 2 weeks. But not sure about it

**Comment by areski** [comment]
Thanks :)

**Comment by illing2005** [comment]
@zhang-z what exactly is missing? Maybe I can help...

**Comment by yangyubo** [comment]
Fixed by PR #101
